export type ResourceSeedValue = string | number | boolean | readonly string[];
export type ResourceSeedRecord = Readonly<Record<string, ResourceSeedValue>>;

const named = (...items: readonly (readonly [name: string, code: string])[]) =>
  items.map(([name, code], sortOrder) => ({ name, code, sortOrder }));

const locationImages = {
  modern: "/discovery/locations/city-modern.jpg",
  heritage: "/discovery/locations/city-heritage.jpg",
  caspian: "/discovery/locations/city-caspian.jpg",
  southCoast: "/discovery/locations/city-south-coast.jpg",
} as const;

export const resourceSeedData: Readonly<
  Record<string, readonly ResourceSeedRecord[]>
> = {
  sport_categories: named(
    ["تناسب اندام", "FITNESS"],
    ["ذهن و بدن", "MIND_BODY"],
    ["ورزش‌های توپی", "BALL_SPORTS"],
    ["ورزش‌های راکتی", "RACQUET_SPORTS"],
    ["ورزش‌های رزمی", "MARTIAL_ARTS"],
    ["ورزش‌های آبی", "WATER_SPORTS"],
    ["استقامتی و هوازی", "ENDURANCE"],
    ["طبیعت و ماجراجویی", "OUTDOOR"],
    ["ژیمناستیک و حرکات نمایشی", "GYMNASTICS"],
  ),
  sports: [
    {
      name: "بدنسازی",
      code: "BODYBUILDING",
      categoryId: "@FITNESS",
      icon: "weight",
      aliases: ["پرورش اندام", "وزنه‌برداری باشگاهی"],
      sortOrder: 1,
    },
    {
      name: "فیتنس",
      code: "FITNESS",
      categoryId: "@FITNESS",
      icon: "person-running",
      aliases: ["تناسب اندام"],
      sortOrder: 2,
    },
    {
      name: "تمرین عملکردی",
      code: "FUNCTIONAL_TRAINING",
      categoryId: "@FITNESS",
      icon: "weight",
      aliases: ["فانکشنال"],
      sortOrder: 3,
    },
    {
      name: "کراس ترینینگ",
      code: "CROSS_TRAINING",
      categoryId: "@FITNESS",
      icon: "weight",
      aliases: ["تمرین ترکیبی"],
      sortOrder: 4,
    },
    {
      name: "ایروبیک",
      code: "AEROBICS",
      categoryId: "@FITNESS",
      icon: "person-running",
      sortOrder: 5,
    },
    {
      name: "اسپینینگ",
      code: "SPINNING",
      categoryId: "@FITNESS",
      icon: "bicycle",
      aliases: ["دوچرخه ثابت گروهی"],
      sortOrder: 6,
    },
    {
      name: "یوگا",
      code: "YOGA",
      categoryId: "@MIND_BODY",
      icon: "person-yoga",
      sortOrder: 7,
    },
    {
      name: "پیلاتس",
      code: "PILATES",
      categoryId: "@MIND_BODY",
      icon: "person-yoga",
      sortOrder: 8,
    },
    {
      name: "تمرینات تعلیقی",
      code: "SUSPENSION_TRAINING",
      categoryId: "@MIND_BODY",
      icon: "person-yoga",
      aliases: ["تی‌آرایکس", "TRX"],
      sortOrder: 9,
    },
    {
      name: "فوتبال",
      code: "FOOTBALL",
      categoryId: "@BALL_SPORTS",
      icon: "soccer-field",
      sortOrder: 10,
    },
    {
      name: "فوتسال",
      code: "FUTSAL",
      categoryId: "@BALL_SPORTS",
      icon: "soccer",
      sortOrder: 11,
    },
    {
      name: "بسکتبال",
      code: "BASKETBALL",
      categoryId: "@BALL_SPORTS",
      icon: "basketball",
      sortOrder: 12,
    },
    {
      name: "والیبال",
      code: "VOLLEYBALL",
      categoryId: "@BALL_SPORTS",
      icon: "volleyball",
      sortOrder: 13,
    },
    {
      name: "هندبال",
      code: "HANDBALL",
      categoryId: "@BALL_SPORTS",
      icon: "volleyball",
      sortOrder: 14,
    },
    {
      name: "تنیس",
      code: "TENNIS",
      categoryId: "@RACQUET_SPORTS",
      icon: "tennis",
      sortOrder: 15,
    },
    {
      name: "بدمینتون",
      code: "BADMINTON",
      categoryId: "@RACQUET_SPORTS",
      icon: "tennis",
      sortOrder: 16,
    },
    {
      name: "تنیس روی میز",
      code: "TABLE_TENNIS",
      categoryId: "@RACQUET_SPORTS",
      icon: "tennis",
      aliases: ["پینگ‌پنگ"],
      sortOrder: 17,
    },
    {
      name: "اسکواش",
      code: "SQUASH",
      categoryId: "@RACQUET_SPORTS",
      icon: "tennis",
      sortOrder: 18,
    },
    {
      name: "پدل",
      code: "PADEL",
      categoryId: "@RACQUET_SPORTS",
      icon: "tennis",
      sortOrder: 19,
    },
    {
      name: "شنا",
      code: "SWIMMING",
      categoryId: "@WATER_SPORTS",
      icon: "person-swimming",
      sortOrder: 20,
    },
    {
      name: "واترپلو",
      code: "WATER_POLO",
      categoryId: "@WATER_SPORTS",
      icon: "person-swimming",
      sortOrder: 21,
    },
    {
      name: "شیرجه",
      code: "DIVING",
      categoryId: "@WATER_SPORTS",
      icon: "person-swimming",
      sortOrder: 22,
    },
    {
      name: "بوکس",
      code: "BOXING",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 23,
    },
    {
      name: "کیک‌بوکسینگ",
      code: "KICKBOXING",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 24,
    },
    {
      name: "کاراته",
      code: "KARATE",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 25,
    },
    {
      name: "تکواندو",
      code: "TAEKWONDO",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 26,
    },
    {
      name: "جودو",
      code: "JUDO",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 27,
    },
    {
      name: "کشتی",
      code: "WRESTLING",
      categoryId: "@MARTIAL_ARTS",
      icon: "boxing",
      sortOrder: 28,
    },
    {
      name: "دویدن",
      code: "RUNNING",
      categoryId: "@ENDURANCE",
      icon: "person-running",
      aliases: ["رانینگ"],
      sortOrder: 29,
    },
    {
      name: "دوچرخه‌سواری",
      code: "CYCLING",
      categoryId: "@ENDURANCE",
      icon: "bicycle",
      sortOrder: 30,
    },
    {
      name: "دو و میدانی",
      code: "ATHLETICS",
      categoryId: "@ENDURANCE",
      icon: "person-running",
      sortOrder: 31,
    },
    {
      name: "سنگ‌نوردی",
      code: "CLIMBING",
      categoryId: "@OUTDOOR",
      icon: "person-hiking",
      aliases: ["صخره‌نوردی"],
      sortOrder: 32,
    },
    {
      name: "کوهنوردی",
      code: "HIKING",
      categoryId: "@OUTDOOR",
      icon: "person-hiking",
      sortOrder: 33,
    },
    {
      name: "ژیمناستیک",
      code: "GYMNASTICS",
      categoryId: "@GYMNASTICS",
      icon: "person-yoga",
      sortOrder: 34,
    },
    {
      name: "پارکور",
      code: "PARKOUR",
      categoryId: "@GYMNASTICS",
      icon: "person-running",
      sortOrder: 35,
    },
  ],
  club_types: [
    { name: "باشگاه بدنسازی", code: "GYM", icon: "weight", sortOrder: 1 },
    {
      name: "مجموعه ورزشی",
      code: "SPORT_COMPLEX",
      icon: "building-1",
      sortOrder: 2,
    },
    { name: "استخر", code: "POOL", icon: "person-swimming", sortOrder: 3 },
    {
      name: "آکادمی تخصصی",
      code: "ACADEMY",
      icon: "academic-cap",
      sortOrder: 4,
    },
    {
      name: "استودیو ورزشی",
      code: "STUDIO",
      icon: "person-yoga",
      sortOrder: 5,
    },
    { name: "سالن رزمی", code: "MARTIAL_ARTS", icon: "boxing", sortOrder: 6 },
    {
      name: "زمین فوتبال",
      code: "FOOTBALL_FIELD",
      icon: "soccer-field",
      sortOrder: 7,
    },
    { name: "باشگاه تنیس", code: "TENNIS", icon: "tennis", sortOrder: 8 },
    {
      name: "سالن والیبال",
      code: "VOLLEYBALL",
      icon: "volleyball",
      sortOrder: 9,
    },
    {
      name: "سالن بسکتبال",
      code: "BASKETBALL_HALL",
      icon: "basketball",
      sortOrder: 10,
    },
    {
      name: "سالن فوتسال",
      code: "FUTSAL_HALL",
      icon: "soccer-field",
      sortOrder: 11,
    },
    {
      name: "باشگاه ورزش‌های آبی",
      code: "AQUATIC_CENTER",
      icon: "person-swimming",
      sortOrder: 12,
    },
    {
      name: "باشگاه سنگ‌نوردی",
      code: "CLIMBING_GYM",
      icon: "person-hiking",
      sortOrder: 13,
    },
    {
      name: "باشگاه پدل",
      code: "PADEL_CLUB",
      icon: "tennis",
      sortOrder: 14,
    },
    {
      name: "پیست دوچرخه‌سواری",
      code: "CYCLING_TRACK",
      icon: "bicycle",
      sortOrder: 15,
    },
  ],
  coach_types: named(
    ["مربی خصوصی", "PERSONAL"],
    ["مربی گروهی", "GROUP"],
    ["مربی آنلاین", "ONLINE"],
    ["مربی باشگاهی", "CLUB"],
    ["مربی تیم", "TEAM"],
    ["مربی کودکان", "KIDS"],
    ["مربی توان‌بخشی ورزشی", "REHABILITATION"],
  ),
  class_types: named(
    ["خصوصی", "PRIVATE"],
    ["نیمه‌خصوصی", "SEMI_PRIVATE"],
    ["گروهی", "GROUP"],
    ["کارگاه آموزشی", "WORKSHOP"],
    ["اردوی ورزشی", "CAMP"],
    ["دوره ترمی", "TERM_COURSE"],
  ),
  court_types: [
    {
      name: "زمین فوتبال",
      code: "FOOTBALL_FIELD",
      supportedSportIds: ["@FOOTBALL"],
    },
    {
      name: "سالن والیبال",
      code: "VOLLEYBALL_HALL",
      supportedSportIds: ["@VOLLEYBALL"],
    },
    {
      name: "استخر سرپوشیده",
      code: "INDOOR_POOL",
      supportedSportIds: ["@SWIMMING"],
    },
    {
      name: "سالن چندمنظوره",
      code: "MULTIPURPOSE_HALL",
      supportedSportIds: ["@FUTSAL", "@VOLLEYBALL", "@BASKETBALL", "@HANDBALL"],
    },
    {
      name: "زمین تنیس",
      code: "TENNIS_COURT",
      supportedSportIds: ["@TENNIS"],
    },
    {
      name: "زمین پدل",
      code: "PADEL_COURT",
      supportedSportIds: ["@PADEL"],
    },
    {
      name: "سالن ورزش‌های راکتی",
      code: "RACQUET_HALL",
      supportedSportIds: ["@BADMINTON", "@TABLE_TENNIS", "@SQUASH"],
    },
    {
      name: "سالن بسکتبال",
      code: "BASKETBALL_COURT",
      supportedSportIds: ["@BASKETBALL"],
    },
    {
      name: "سالن رزمی",
      code: "COMBAT_HALL",
      supportedSportIds: [
        "@BOXING",
        "@KICKBOXING",
        "@KARATE",
        "@TAEKWONDO",
        "@JUDO",
        "@WRESTLING",
      ],
    },
    {
      name: "دیواره سنگ‌نوردی",
      code: "CLIMBING_WALL",
      supportedSportIds: ["@CLIMBING"],
    },
  ],
  coach_specialties: [
    {
      name: "عضله‌سازی و افزایش قدرت",
      code: "STRENGTH",
      sportIds: ["@BODYBUILDING", "@FITNESS"],
    },
    { name: "کاهش وزن", code: "WEIGHT_LOSS", sportIds: ["@FITNESS"] },
    { name: "تکنیک بوکس", code: "BOXING_TECHNIQUE", sportIds: ["@BOXING"] },
    {
      name: "اصلاح فرم و پیشگیری از آسیب",
      code: "CORRECTIVE_EXERCISE",
      sportIds: ["@FITNESS", "@FUNCTIONAL_TRAINING", "@PILATES"],
    },
    {
      name: "آمادگی جسمانی حرفه‌ای",
      code: "ATHLETIC_CONDITIONING",
      sportIds: ["@FUNCTIONAL_TRAINING", "@RUNNING", "@ATHLETICS"],
    },
    {
      name: "یوگا و تنفس",
      code: "YOGA_BREATHWORK",
      sportIds: ["@YOGA"],
    },
    {
      name: "آموزش شنا",
      code: "SWIMMING_EDUCATION",
      sportIds: ["@SWIMMING"],
    },
    {
      name: "مربیگری فوتبال و فوتسال",
      code: "FOOTBALL_COACHING",
      sportIds: ["@FOOTBALL", "@FUTSAL"],
    },
    {
      name: "ورزش کودکان",
      code: "KIDS_SPORT",
      sportIds: ["@GYMNASTICS", "@SWIMMING"],
    },
    {
      name: "تمرینات استقامتی",
      code: "ENDURANCE_COACHING",
      sportIds: ["@RUNNING", "@CYCLING", "@ATHLETICS"],
    },
    {
      name: "آموزش ورزش‌های راکتی",
      code: "RACQUET_COACHING",
      sportIds: ["@TENNIS", "@BADMINTON", "@PADEL"],
    },
  ],
  skill_levels: named(
    ["مبتدی", "BEGINNER"],
    ["متوسط", "INTERMEDIATE"],
    ["پیشرفته", "ADVANCED"],
    ["حرفه‌ای", "PROFESSIONAL"],
  ),

  amenity_categories: named(
    ["رفاهی", "COMFORT"],
    ["بهداشتی", "HYGIENE"],
    ["دسترسی", "ACCESSIBILITY"],
    ["ایمنی", "SAFETY"],
    ["فناوری", "TECHNOLOGY"],
    ["خانواده", "FAMILY"],
  ),
  amenities: [
    { name: "رختکن", code: "LOCKER_ROOM", categoryId: "@COMFORT" },
    { name: "دوش", code: "SHOWER", categoryId: "@HYGIENE" },
    { name: "پارکینگ", code: "PARKING", categoryId: "@ACCESSIBILITY" },
    { name: "کمد اختصاصی", code: "LOCKER", categoryId: "@COMFORT" },
    { name: "تهویه مطبوع", code: "AIR_CONDITIONING", categoryId: "@COMFORT" },
    { name: "سونا", code: "SAUNA", categoryId: "@COMFORT" },
    { name: "جکوزی", code: "JACUZZI", categoryId: "@COMFORT" },
    { name: "آب‌سردکن", code: "WATER_DISPENSER", categoryId: "@COMFORT" },
    { name: "سرویس بهداشتی", code: "RESTROOM", categoryId: "@HYGIENE" },
    {
      name: "ضدعفونی تجهیزات",
      code: "EQUIPMENT_SANITATION",
      categoryId: "@HYGIENE",
    },
    {
      name: "دسترسی ویلچر",
      code: "WHEELCHAIR_ACCESS",
      categoryId: "@ACCESSIBILITY",
    },
    { name: "آسانسور", code: "ELEVATOR", categoryId: "@ACCESSIBILITY" },
    { name: "کمک‌های اولیه", code: "FIRST_AID", categoryId: "@SAFETY" },
    { name: "دستگاه شوک قلبی", code: "AED", categoryId: "@SAFETY" },
    { name: "نگهبانی", code: "SECURITY", categoryId: "@SAFETY" },
    { name: "اینترنت بی‌سیم", code: "WIFI", categoryId: "@TECHNOLOGY" },
    {
      name: "ثبت ورود دیجیتال",
      code: "DIGITAL_CHECK_IN",
      categoryId: "@TECHNOLOGY",
    },
    { name: "فضای انتظار", code: "WAITING_AREA", categoryId: "@FAMILY" },
    { name: "فضای کودک", code: "KIDS_AREA", categoryId: "@FAMILY" },
  ],
  equipment_categories: named(
    ["قدرتی", "STRENGTH"],
    ["هوازی", "CARDIO"],
    ["تمرین آزاد", "FREE_WEIGHT"],
    ["کششی و تعادلی", "MOBILITY"],
    ["ورزش‌های توپی", "BALL_EQUIPMENT"],
    ["ورزش‌های راکتی", "RACQUET_EQUIPMENT"],
    ["ورزش‌های رزمی", "COMBAT_EQUIPMENT"],
    ["ورزش‌های آبی", "AQUATIC_EQUIPMENT"],
  ),
  equipment: [
    {
      name: "تردمیل",
      code: "TREADMILL",
      categoryId: "@CARDIO",
      sportIds: ["@FITNESS"],
    },
    {
      name: "دوچرخه ثابت",
      code: "STATIONARY_BIKE",
      categoryId: "@CARDIO",
      sportIds: ["@FITNESS"],
    },
    {
      name: "دمبل",
      code: "DUMBBELL",
      categoryId: "@FREE_WEIGHT",
      sportIds: ["@BODYBUILDING", "@FITNESS"],
    },
    {
      name: "هالتر و صفحه وزنه",
      code: "BARBELL",
      categoryId: "@FREE_WEIGHT",
      sportIds: ["@BODYBUILDING"],
    },
    {
      name: "دستگاه اسمیت",
      code: "SMITH_MACHINE",
      categoryId: "@STRENGTH",
      sportIds: ["@BODYBUILDING"],
    },
    {
      name: "لت سیم‌کش",
      code: "LAT_PULLDOWN",
      categoryId: "@STRENGTH",
      sportIds: ["@BODYBUILDING"],
    },
    {
      name: "دستگاه پرس پا",
      code: "LEG_PRESS",
      categoryId: "@STRENGTH",
      sportIds: ["@BODYBUILDING", "@FITNESS"],
    },
    {
      name: "الپتیکال",
      code: "ELLIPTICAL",
      categoryId: "@CARDIO",
      sportIds: ["@FITNESS"],
    },
    {
      name: "دستگاه روئینگ",
      code: "ROWING_MACHINE",
      categoryId: "@CARDIO",
      sportIds: ["@FITNESS", "@FUNCTIONAL_TRAINING"],
    },
    {
      name: "کتل‌بل",
      code: "KETTLEBELL",
      categoryId: "@FREE_WEIGHT",
      sportIds: ["@FITNESS", "@FUNCTIONAL_TRAINING", "@CROSS_TRAINING"],
    },
    {
      name: "کش مقاومتی",
      code: "RESISTANCE_BAND",
      categoryId: "@MOBILITY",
      sportIds: ["@FITNESS", "@PILATES", "@SUSPENSION_TRAINING"],
    },
    {
      name: "مت ورزشی",
      code: "EXERCISE_MAT",
      categoryId: "@MOBILITY",
      sportIds: ["@YOGA", "@PILATES", "@FITNESS"],
    },
    {
      name: "توپ فوتبال و فوتسال",
      code: "FOOTBALL_BALL",
      categoryId: "@BALL_EQUIPMENT",
      sportIds: ["@FOOTBALL", "@FUTSAL"],
    },
    {
      name: "توپ بسکتبال",
      code: "BASKETBALL_BALL",
      categoryId: "@BALL_EQUIPMENT",
      sportIds: ["@BASKETBALL"],
    },
    {
      name: "توپ والیبال",
      code: "VOLLEYBALL_BALL",
      categoryId: "@BALL_EQUIPMENT",
      sportIds: ["@VOLLEYBALL"],
    },
    {
      name: "راکت تنیس",
      code: "TENNIS_RACKET",
      categoryId: "@RACQUET_EQUIPMENT",
      sportIds: ["@TENNIS"],
    },
    {
      name: "راکت پدل",
      code: "PADEL_RACKET",
      categoryId: "@RACQUET_EQUIPMENT",
      sportIds: ["@PADEL"],
    },
    {
      name: "کیسه بوکس",
      code: "PUNCHING_BAG",
      categoryId: "@COMBAT_EQUIPMENT",
      sportIds: ["@BOXING", "@KICKBOXING"],
    },
    {
      name: "تخته شنا",
      code: "KICKBOARD",
      categoryId: "@AQUATIC_EQUIPMENT",
      sportIds: ["@SWIMMING"],
    },
  ],
  court_surface_types: named(
    ["چمن طبیعی", "NATURAL_GRASS"],
    ["چمن مصنوعی", "ARTIFICIAL_GRASS"],
    ["پارکت", "PARQUET"],
    ["تارتان", "TARTAN"],
    ["کف‌پوش ورزشی", "SPORT_FLOOR"],
    ["هاردکورت", "HARD_COURT"],
    ["خاک رس", "CLAY"],
    ["آسفالت", "ASPHALT"],
    ["تشک تاتامی", "TATAMI"],
  ),
  court_feature_types: named(
    ["سرپوشیده", "INDOOR"],
    ["روباز", "OUTDOOR"],
    ["نورپردازی شب", "NIGHT_LIGHTING"],
    ["سکوی تماشاگر", "BLEACHERS"],
    ["رختکن اختصاصی", "DEDICATED_LOCKER_ROOM"],
    ["تابلوی امتیاز", "SCOREBOARD"],
    ["تهویه سالن", "HALL_VENTILATION"],
    ["پخش زنده", "LIVE_STREAMING"],
  ),
  service_types: named(
    ["برنامه تمرینی", "WORKOUT_PLAN"],
    ["مشاوره تغذیه", "NUTRITION"],
    ["ارزیابی بدنی", "BODY_ASSESSMENT"],
    ["مربی خصوصی", "PERSONAL_TRAINING"],
    ["اصلاح حرکتی", "CORRECTIVE_EXERCISE"],
    ["فیزیوتراپی ورزشی", "SPORTS_PHYSIOTHERAPY"],
    ["ماساژ ورزشی", "SPORTS_MASSAGE"],
    ["آنالیز ترکیب بدنی", "BODY_COMPOSITION"],
    ["ریکاوری ورزشی", "SPORT_RECOVERY"],
    ["آمادگی مسابقه", "COMPETITION_PREP"],
    ["برنامه آنلاین", "ONLINE_PROGRAM"],
  ),

  countries: [
    { name: "ایران", code: "IR", aliases: ["جمهوری اسلامی ایران", "Iran"] },
  ],
  provinces: [
    {
      name: "تهران",
      code: "TEHRAN",
      slug: "tehran-province",
      countryId: "@IR",
    },
    { name: "البرز", code: "ALBORZ", slug: "alborz", countryId: "@IR" },
    {
      name: "خراسان رضوی",
      code: "RAZAVI_KHORASAN",
      slug: "razavi-khorasan",
      countryId: "@IR",
    },
    {
      name: "اصفهان",
      code: "ISFAHAN",
      slug: "isfahan-province",
      countryId: "@IR",
    },
    { name: "فارس", code: "FARS", slug: "fars", countryId: "@IR" },
    {
      name: "آذربایجان شرقی",
      code: "EAST_AZERBAIJAN",
      slug: "east-azerbaijan",
      countryId: "@IR",
    },
    { name: "خوزستان", code: "KHUZESTAN", slug: "khuzestan", countryId: "@IR" },
    { name: "قم", code: "QOM", slug: "qom-province", countryId: "@IR" },
    { name: "گیلان", code: "GILAN", slug: "gilan", countryId: "@IR" },
    {
      name: "مازندران",
      code: "MAZANDARAN",
      slug: "mazandaran",
      countryId: "@IR",
    },
    { name: "یزد", code: "YAZD", slug: "yazd-province", countryId: "@IR" },
    {
      name: "کرمان",
      code: "KERMAN",
      slug: "kerman-province",
      countryId: "@IR",
    },
    { name: "هرمزگان", code: "HORMOZGAN", slug: "hormozgan", countryId: "@IR" },
  ],
  cities: [
    {
      name: "تهران",
      code: "TEHRAN_CITY",
      slug: "tehran",
      provinceId: "@TEHRAN",
      imageUrl: locationImages.modern,
      description: "باشگاه‌ها، کلاس‌ها و مربی‌های فعال در سراسر تهران",
    },
    {
      name: "کرج",
      code: "KARAJ",
      slug: "karaj",
      provinceId: "@ALBORZ",
      imageUrl: locationImages.modern,
    },
    {
      name: "مشهد",
      code: "MASHHAD",
      slug: "mashhad",
      provinceId: "@RAZAVI_KHORASAN",
      imageUrl: locationImages.modern,
    },
    {
      name: "اصفهان",
      code: "ISFAHAN_CITY",
      slug: "isfahan",
      provinceId: "@ISFAHAN",
      imageUrl: locationImages.heritage,
    },
    {
      name: "شیراز",
      code: "SHIRAZ",
      slug: "shiraz",
      provinceId: "@FARS",
      imageUrl: locationImages.heritage,
    },
    {
      name: "تبریز",
      code: "TABRIZ",
      slug: "tabriz",
      provinceId: "@EAST_AZERBAIJAN",
      imageUrl: locationImages.modern,
    },
    {
      name: "اهواز",
      code: "AHVAZ",
      slug: "ahvaz",
      provinceId: "@KHUZESTAN",
      imageUrl: locationImages.southCoast,
    },
    {
      name: "قم",
      code: "QOM_CITY",
      slug: "qom",
      provinceId: "@QOM",
      imageUrl: locationImages.modern,
    },
    {
      name: "رشت",
      code: "RASHT",
      slug: "rasht",
      provinceId: "@GILAN",
      imageUrl: locationImages.caspian,
    },
    {
      name: "ساری",
      code: "SARI",
      slug: "sari",
      provinceId: "@MAZANDARAN",
      imageUrl: locationImages.caspian,
    },
    {
      name: "یزد",
      code: "YAZD_CITY",
      slug: "yazd",
      provinceId: "@YAZD",
      imageUrl: locationImages.heritage,
    },
    {
      name: "کرمان",
      code: "KERMAN_CITY",
      slug: "kerman",
      provinceId: "@KERMAN",
      imageUrl: locationImages.heritage,
    },
    {
      name: "بندرعباس",
      code: "BANDAR_ABBAS",
      slug: "bandar-abbas",
      provinceId: "@HORMOZGAN",
      imageUrl: locationImages.southCoast,
      aliases: ["بندر عباس"],
    },
    {
      name: "کیش",
      code: "KISH",
      slug: "kish",
      provinceId: "@HORMOZGAN",
      imageUrl: locationImages.southCoast,
    },
  ],
  districts: [
    ...(
      [
        ["منطقه ۱", "TEHRAN_DISTRICT_1", "tehran-district-1"],
        ["منطقه ۲", "TEHRAN_DISTRICT_2", "tehran-district-2"],
        ["منطقه ۳", "TEHRAN_DISTRICT_3", "tehran-district-3"],
        ["منطقه ۴", "TEHRAN_DISTRICT_4", "tehran-district-4"],
        ["منطقه ۵", "TEHRAN_DISTRICT_5", "tehran-district-5"],
        ["منطقه ۶", "TEHRAN_DISTRICT_6", "tehran-district-6"],
        ["منطقه ۷", "TEHRAN_DISTRICT_7", "tehran-district-7"],
        ["منطقه ۸", "TEHRAN_DISTRICT_8", "tehran-district-8"],
        ["منطقه ۱۰", "TEHRAN_DISTRICT_10", "tehran-district-10"],
        ["منطقه ۲۲", "TEHRAN_DISTRICT_22", "tehran-district-22"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: "@TEHRAN_CITY",
      imageUrl: locationImages.modern,
    })),
    ...(
      [
        ["منطقه ۱ کرج", "KARAJ_DISTRICT_1", "karaj-district-1"],
        ["منطقه ۴ کرج", "KARAJ_DISTRICT_4", "karaj-district-4"],
        ["منطقه ۸ کرج", "KARAJ_DISTRICT_8", "karaj-district-8"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: "@KARAJ",
      imageUrl: locationImages.modern,
    })),
    ...(
      [
        ["منطقه ۱ مشهد", "MASHHAD_DISTRICT_1", "mashhad-district-1"],
        ["منطقه ۹ مشهد", "MASHHAD_DISTRICT_9", "mashhad-district-9"],
        ["منطقه ۱۱ مشهد", "MASHHAD_DISTRICT_11", "mashhad-district-11"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: "@MASHHAD",
      imageUrl: locationImages.modern,
    })),
    ...(
      [
        ["منطقه ۳ اصفهان", "ISFAHAN_DISTRICT_3", "isfahan-district-3"],
        ["منطقه ۵ اصفهان", "ISFAHAN_DISTRICT_5", "isfahan-district-5"],
        ["منطقه ۶ اصفهان", "ISFAHAN_DISTRICT_6", "isfahan-district-6"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: "@ISFAHAN_CITY",
      imageUrl: locationImages.heritage,
    })),
    ...(
      [
        ["منطقه ۱ شیراز", "SHIRAZ_DISTRICT_1", "shiraz-district-1"],
        ["منطقه ۶ شیراز", "SHIRAZ_DISTRICT_6", "shiraz-district-6"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: "@SHIRAZ",
      imageUrl: locationImages.heritage,
    })),
    ...(
      [
        ["منطقه ۱ تبریز", "TABRIZ_DISTRICT_1", "tabriz-district-1"],
        ["منطقه ۲ تبریز", "TABRIZ_DISTRICT_2", "tabriz-district-2"],
        ["منطقه ۲ اهواز", "AHVAZ_DISTRICT_2", "ahvaz-district-2"],
        ["منطقه ۳ اهواز", "AHVAZ_DISTRICT_3", "ahvaz-district-3"],
        ["منطقه ۱ قم", "QOM_DISTRICT_1", "qom-district-1"],
        ["منطقه ۸ قم", "QOM_DISTRICT_8", "qom-district-8"],
      ] as const
    ).map(([name, code, slug]) => ({
      name,
      code,
      slug,
      cityId: code.startsWith("TABRIZ")
        ? "@TABRIZ"
        : code.startsWith("AHVAZ")
          ? "@AHVAZ"
          : "@QOM_CITY",
      imageUrl: code.startsWith("AHVAZ")
        ? locationImages.southCoast
        : locationImages.modern,
    })),
    ...(
      [
        ["منطقه ۱ رشت", "RASHT_DISTRICT_1", "rasht-district-1", "@RASHT"],
        ["منطقه ۳ رشت", "RASHT_DISTRICT_3", "rasht-district-3", "@RASHT"],
        ["منطقه ۱ ساری", "SARI_DISTRICT_1", "sari-district-1", "@SARI"],
      ] as const
    ).map(([name, code, slug, cityId]) => ({
      name,
      code,
      slug,
      cityId,
      imageUrl: locationImages.caspian,
    })),
    ...(
      [
        ["منطقه ۱ یزد", "YAZD_DISTRICT_1", "yazd-district-1", "@YAZD_CITY"],
        [
          "منطقه ۱ کرمان",
          "KERMAN_DISTRICT_1",
          "kerman-district-1",
          "@KERMAN_CITY",
        ],
      ] as const
    ).map(([name, code, slug, cityId]) => ({
      name,
      code,
      slug,
      cityId,
      imageUrl: locationImages.heritage,
    })),
    ...(
      [
        [
          "منطقه ۱ بندرعباس",
          "BANDAR_ABBAS_DISTRICT_1",
          "bandar-abbas-district-1",
          "@BANDAR_ABBAS",
        ],
        ["مرکز جزیره کیش", "KISH_CENTER", "kish-center", "@KISH"],
      ] as const
    ).map(([name, code, slug, cityId]) => ({
      name,
      code,
      slug,
      cityId,
      imageUrl: locationImages.southCoast,
    })),
  ],
  neighborhoods: [
    { name: "تجریش", code: "TAJRISH", districtId: "@TEHRAN_DISTRICT_1" },
    { name: "زعفرانیه", code: "ZAFARANIYEH", districtId: "@TEHRAN_DISTRICT_1" },
    { name: "نیاوران", code: "NIAVARAN", districtId: "@TEHRAN_DISTRICT_1" },
    { name: "الهیه", code: "ELAHIEH", districtId: "@TEHRAN_DISTRICT_1" },
    { name: "فرمانیه", code: "FARMANIEH", districtId: "@TEHRAN_DISTRICT_1" },
    {
      name: "سعادت‌آباد",
      code: "SAADAT_ABAD",
      districtId: "@TEHRAN_DISTRICT_2",
    },
    {
      name: "شهرک غرب",
      code: "SHAHRAK_GHARB",
      districtId: "@TEHRAN_DISTRICT_2",
    },
    { name: "مرزداران", code: "MARZDARAN", districtId: "@TEHRAN_DISTRICT_2" },
    { name: "ستارخان", code: "SATTARKHAN", districtId: "@TEHRAN_DISTRICT_2" },
    { name: "گیشا", code: "GISHA", districtId: "@TEHRAN_DISTRICT_2" },
    { name: "ونک", code: "VANAK", districtId: "@TEHRAN_DISTRICT_3" },
    { name: "میرداماد", code: "MIRDAMAD", districtId: "@TEHRAN_DISTRICT_3" },
    { name: "اختیاریه", code: "EKHTIARIEH", districtId: "@TEHRAN_DISTRICT_3" },
    { name: "تهرانپارس", code: "TEHRANPARS", districtId: "@TEHRAN_DISTRICT_4" },
    { name: "حکیمیه", code: "HAKIMIEH", districtId: "@TEHRAN_DISTRICT_4" },
    { name: "پونک", code: "PUNAK", districtId: "@TEHRAN_DISTRICT_5" },
    { name: "جنت‌آباد", code: "JANNAT_ABAD", districtId: "@TEHRAN_DISTRICT_5" },
    { name: "شهران", code: "SHAHRAN", districtId: "@TEHRAN_DISTRICT_5" },
    {
      name: "یوسف‌آباد",
      code: "YOUSOF_ABAD",
      districtId: "@TEHRAN_DISTRICT_6",
    },
    { name: "امیرآباد", code: "AMIR_ABAD", districtId: "@TEHRAN_DISTRICT_6" },
    { name: "فاطمی", code: "FATEMI", districtId: "@TEHRAN_DISTRICT_6" },
    { name: "عباس‌آباد", code: "ABBAS_ABAD", districtId: "@TEHRAN_DISTRICT_7" },
    { name: "سهروردی", code: "SOHREVARDI", districtId: "@TEHRAN_DISTRICT_7" },
    { name: "هفت‌تیر", code: "HAFT_TIR", districtId: "@TEHRAN_DISTRICT_7" },
    { name: "نارمک", code: "NARMAK", districtId: "@TEHRAN_DISTRICT_8" },
    { name: "مدائن", code: "MADAYEN", districtId: "@TEHRAN_DISTRICT_8" },
    { name: "جیحون", code: "JEYHOON", districtId: "@TEHRAN_DISTRICT_10" },
    { name: "بریانک", code: "BERYANAK", districtId: "@TEHRAN_DISTRICT_10" },
    { name: "چیتگر", code: "CHITGAR", districtId: "@TEHRAN_DISTRICT_22" },
    {
      name: "شهرک گلستان",
      code: "SHAHRAK_GOLESTAN",
      districtId: "@TEHRAN_DISTRICT_22",
    },
    { name: "زیبادشت", code: "ZIBADASHT", districtId: "@TEHRAN_DISTRICT_22" },
    { name: "عظیمیه", code: "AZIMIEH", districtId: "@KARAJ_DISTRICT_1" },
    { name: "جهانشهر", code: "JAHANSHAHR", districtId: "@KARAJ_DISTRICT_1" },
    { name: "مهرشهر", code: "MEHRSHAHR", districtId: "@KARAJ_DISTRICT_4" },
    {
      name: "باغستان کرج",
      code: "BAGHESTAN_KARAJ",
      districtId: "@KARAJ_DISTRICT_4",
    },
    { name: "گوهردشت", code: "GOHARDASHT", districtId: "@KARAJ_DISTRICT_8" },
    {
      name: "حصارک کرج",
      code: "HESARAK_KARAJ",
      districtId: "@KARAJ_DISTRICT_8",
    },
    {
      name: "سجادشهر",
      code: "SAJJAD_SHAHR",
      districtId: "@MASHHAD_DISTRICT_1",
    },
    {
      name: "احمدآباد مشهد",
      code: "AHMADABAD_MASHHAD",
      districtId: "@MASHHAD_DISTRICT_1",
    },
    { name: "ملک‌آباد", code: "MOLK_ABAD", districtId: "@MASHHAD_DISTRICT_1" },
    { name: "هاشمیه", code: "HASHEMIEH", districtId: "@MASHHAD_DISTRICT_9" },
    {
      name: "هنرستان مشهد",
      code: "HONARESTAN_MASHHAD",
      districtId: "@MASHHAD_DISTRICT_9",
    },
    {
      name: "الهیه مشهد",
      code: "ELAHIEH_MASHHAD",
      districtId: "@MASHHAD_DISTRICT_11",
    },
    { name: "خواجو", code: "KHAJOO", districtId: "@ISFAHAN_DISTRICT_3" },
    {
      name: "بزرگمهر اصفهان",
      code: "BOZORGMEHR_ISFAHAN",
      districtId: "@ISFAHAN_DISTRICT_3",
    },
    { name: "جلفا", code: "JOLFA", districtId: "@ISFAHAN_DISTRICT_5" },
    { name: "مرداویج", code: "MARDAVIJ", districtId: "@ISFAHAN_DISTRICT_5" },
    {
      name: "سپاهان‌شهر",
      code: "SEPAHAN_SHAHR",
      districtId: "@ISFAHAN_DISTRICT_6",
    },
    {
      name: "هزارجریب",
      code: "HEZAR_JARIB",
      districtId: "@ISFAHAN_DISTRICT_6",
    },
    { name: "قصرالدشت", code: "GHASR_DASHT", districtId: "@SHIRAZ_DISTRICT_1" },
    { name: "عفیف‌آباد", code: "AFIF_ABAD", districtId: "@SHIRAZ_DISTRICT_1" },
    {
      name: "معالی‌آباد",
      code: "MAALI_ABAD",
      districtId: "@SHIRAZ_DISTRICT_6",
    },
    {
      name: "فرهنگ‌شهر شیراز",
      code: "FARHANG_SHAHR_SHIRAZ",
      districtId: "@SHIRAZ_DISTRICT_6",
    },
    {
      name: "ولیعصر تبریز",
      code: "VALIASR_TABRIZ",
      districtId: "@TABRIZ_DISTRICT_1",
    },
    { name: "ائل‌گلی", code: "EL_GOLI", districtId: "@TABRIZ_DISTRICT_1" },
    { name: "آبرسان", code: "ABRESAN", districtId: "@TABRIZ_DISTRICT_2" },
    {
      name: "مرزداران تبریز",
      code: "MARZDARAN_TABRIZ",
      districtId: "@TABRIZ_DISTRICT_2",
    },
    { name: "کیانپارس", code: "KIANPARS", districtId: "@AHVAZ_DISTRICT_2" },
    { name: "کیان‌آباد", code: "KIAN_ABAD", districtId: "@AHVAZ_DISTRICT_2" },
    {
      name: "زیتون کارمندی",
      code: "ZEYTOON_KARMANDI",
      districtId: "@AHVAZ_DISTRICT_3",
    },
    {
      name: "گلستان اهواز",
      code: "GOLESTAN_AHVAZ",
      districtId: "@AHVAZ_DISTRICT_3",
    },
    { name: "سالاریه", code: "SALARIEH", districtId: "@QOM_DISTRICT_1" },
    { name: "صفاشهر قم", code: "SAFASHAHR_QOM", districtId: "@QOM_DISTRICT_1" },
    { name: "پردیسان", code: "PARDISAN", districtId: "@QOM_DISTRICT_8" },
    { name: "بنیادیان", code: "BONYADIAN", districtId: "@QOM_DISTRICT_8" },
    { name: "گلسار", code: "GOLSAR", districtId: "@RASHT_DISTRICT_1" },
    {
      name: "منظریه رشت",
      code: "MANZARIEH_RASHT",
      districtId: "@RASHT_DISTRICT_1",
    },
    {
      name: "معلم رشت",
      code: "MOALLEM_RASHT",
      districtId: "@RASHT_DISTRICT_3",
    },
    { name: "لاکانی", code: "LAKANI", districtId: "@RASHT_DISTRICT_3" },
    {
      name: "فرهنگ ساری",
      code: "FARHANG_SARI",
      districtId: "@SARI_DISTRICT_1",
    },
    {
      name: "کشاورز ساری",
      code: "KESHAVARZ_SARI",
      districtId: "@SARI_DISTRICT_1",
    },
    { name: "میرزمانی", code: "MIRZAMANI", districtId: "@SARI_DISTRICT_1" },
    {
      name: "صفائیه یزد",
      code: "SAFAIEH_YAZD",
      districtId: "@YAZD_DISTRICT_1",
    },
    {
      name: "امام‌شهر یزد",
      code: "EMAM_SHAHR_YAZD",
      districtId: "@YAZD_DISTRICT_1",
    },
    {
      name: "آزادشهر یزد",
      code: "AZAD_SHAHR_YAZD",
      districtId: "@YAZD_DISTRICT_1",
    },
    {
      name: "هزارویک‌شب",
      code: "HEZARO_YEK_SHAB",
      districtId: "@KERMAN_DISTRICT_1",
    },
    {
      name: "بلوار جمهوری کرمان",
      code: "JOMHOURI_KERMAN",
      districtId: "@KERMAN_DISTRICT_1",
    },
    {
      name: "مطهری کرمان",
      code: "MOTAHARI_KERMAN",
      districtId: "@KERMAN_DISTRICT_1",
    },
    {
      name: "گلشهر بندرعباس",
      code: "GOLSHAHR_BANDAR_ABBAS",
      districtId: "@BANDAR_ABBAS_DISTRICT_1",
    },
    {
      name: "نخل ناخدا",
      code: "NAKHL_NAKHODA",
      districtId: "@BANDAR_ABBAS_DISTRICT_1",
    },
    { name: "سورو", code: "SORO", districtId: "@BANDAR_ABBAS_DISTRICT_1" },
    { name: "شهرک صدف کیش", code: "SADAF_KISH", districtId: "@KISH_CENTER" },
    { name: "سفین", code: "SAFIN", districtId: "@KISH_CENTER" },
  ],
  city_regions: [
    { name: "شمال تهران", code: "TEHRAN_NORTH", cityId: "@TEHRAN_CITY" },
    { name: "مرکز تهران", code: "TEHRAN_CENTER", cityId: "@TEHRAN_CITY" },
    { name: "غرب تهران", code: "TEHRAN_WEST", cityId: "@TEHRAN_CITY" },
    { name: "شرق تهران", code: "TEHRAN_EAST", cityId: "@TEHRAN_CITY" },
    { name: "جنوب تهران", code: "TEHRAN_SOUTH", cityId: "@TEHRAN_CITY" },
    { name: "مرکز کرج", code: "KARAJ_CENTER", cityId: "@KARAJ" },
    { name: "غرب کرج", code: "KARAJ_WEST", cityId: "@KARAJ" },
    { name: "شرق کرج", code: "KARAJ_EAST", cityId: "@KARAJ" },
    { name: "مرکز مشهد", code: "MASHHAD_CENTER", cityId: "@MASHHAD" },
    { name: "غرب مشهد", code: "MASHHAD_WEST", cityId: "@MASHHAD" },
    { name: "شمال مشهد", code: "MASHHAD_NORTH", cityId: "@MASHHAD" },
    { name: "مرکز اصفهان", code: "ISFAHAN_CENTER", cityId: "@ISFAHAN_CITY" },
    { name: "جنوب اصفهان", code: "ISFAHAN_SOUTH", cityId: "@ISFAHAN_CITY" },
    { name: "غرب اصفهان", code: "ISFAHAN_WEST", cityId: "@ISFAHAN_CITY" },
    { name: "مرکز شیراز", code: "SHIRAZ_CENTER", cityId: "@SHIRAZ" },
    { name: "شمال‌غرب شیراز", code: "SHIRAZ_NORTHWEST", cityId: "@SHIRAZ" },
    { name: "شرق تبریز", code: "TABRIZ_EAST", cityId: "@TABRIZ" },
    { name: "مرکز تبریز", code: "TABRIZ_CENTER", cityId: "@TABRIZ" },
    { name: "شرق اهواز", code: "AHVAZ_EAST", cityId: "@AHVAZ" },
    { name: "غرب اهواز", code: "AHVAZ_WEST", cityId: "@AHVAZ" },
    { name: "مرکز قم", code: "QOM_CENTER", cityId: "@QOM_CITY" },
    { name: "غرب قم", code: "QOM_WEST", cityId: "@QOM_CITY" },
    { name: "مرکز رشت", code: "RASHT_CENTER", cityId: "@RASHT" },
    { name: "غرب رشت", code: "RASHT_WEST", cityId: "@RASHT" },
    { name: "مرکز ساری", code: "SARI_CENTER", cityId: "@SARI" },
    { name: "مرکز یزد", code: "YAZD_CENTER", cityId: "@YAZD_CITY" },
    { name: "مرکز کرمان", code: "KERMAN_CENTER", cityId: "@KERMAN_CITY" },
    {
      name: "مرکز بندرعباس",
      code: "BANDAR_ABBAS_CENTER",
      cityId: "@BANDAR_ABBAS",
    },
    { name: "جزیره کیش", code: "KISH_ISLAND", cityId: "@KISH" },
  ],

  class_goal_types: [
    {
      name: "کاهش وزن",
      code: "WEIGHT_LOSS",
      sportIds: ["@FITNESS", "@AEROBICS", "@SPINNING", "@RUNNING"],
    },
    {
      name: "افزایش قدرت",
      code: "STRENGTH_GAIN",
      sportIds: ["@BODYBUILDING", "@FUNCTIONAL_TRAINING", "@CROSS_TRAINING"],
    },
    {
      name: "یادگیری مهارت",
      code: "SKILL_LEARNING",
      sportIds: ["@BOXING", "@SWIMMING", "@TENNIS", "@GYMNASTICS"],
    },
    {
      name: "افزایش انعطاف‌پذیری",
      code: "FLEXIBILITY",
      sportIds: ["@YOGA", "@PILATES", "@GYMNASTICS"],
    },
    {
      name: "بهبود استقامت",
      code: "ENDURANCE",
      sportIds: ["@RUNNING", "@CYCLING", "@SWIMMING", "@ATHLETICS"],
    },
    {
      name: "اصلاح فرم حرکتی",
      code: "MOVEMENT_CORRECTION",
      sportIds: ["@FITNESS", "@PILATES", "@FUNCTIONAL_TRAINING"],
    },
    {
      name: "آمادگی مسابقه",
      code: "COMPETITION_PREP",
      sportIds: ["@BODYBUILDING", "@BOXING", "@RUNNING", "@SWIMMING"],
    },
    {
      name: "تفریح و فعالیت گروهی",
      code: "RECREATION",
      sportIds: ["@FOOTBALL", "@FUTSAL", "@VOLLEYBALL", "@BASKETBALL"],
    },
  ],
  class_intensity_levels: named(
    ["سبک", "LOW"],
    ["متوسط", "MEDIUM"],
    ["شدید", "HIGH"],
  ),
  class_skill_levels: named(
    ["مقدماتی", "BEGINNER"],
    ["متوسط", "INTERMEDIATE"],
    ["پیشرفته", "ADVANCED"],
  ),
  class_format_types: named(
    ["حضوری", "IN_PERSON"],
    ["آنلاین", "ONLINE"],
    ["ترکیبی", "HYBRID"],
  ),
  required_item_types: [
    {
      name: "کفش ورزشی",
      code: "SPORT_SHOES",
      sportIds: ["@FITNESS", "@VOLLEYBALL", "@RUNNING", "@BASKETBALL"],
    },
    { name: "دستکش بوکس", code: "BOXING_GLOVES", sportIds: ["@BOXING"] },
    { name: "مایو و کلاه شنا", code: "SWIMWEAR", sportIds: ["@SWIMMING"] },
    {
      name: "مت شخصی",
      code: "PERSONAL_MAT",
      sportIds: ["@YOGA", "@PILATES"],
    },
    {
      name: "راکت شخصی",
      code: "PERSONAL_RACKET",
      sportIds: ["@TENNIS", "@BADMINTON", "@PADEL"],
    },
    {
      name: "قمقمه آب",
      code: "WATER_BOTTLE",
      sportIds: ["@FITNESS", "@RUNNING", "@CYCLING", "@HIKING"],
    },
    {
      name: "حوله ورزشی",
      code: "SPORT_TOWEL",
      sportIds: ["@FITNESS", "@BODYBUILDING", "@SWIMMING"],
    },
  ],
  age_group_presets: [
    { name: "خردسالان", minAge: 3, maxAge: 5 },
    { name: "کودکان", minAge: 6, maxAge: 11 },
    { name: "نوجوانان", minAge: 12, maxAge: 17 },
    { name: "بزرگسالان", minAge: 18, maxAge: 59 },
    { name: "سالمندان", minAge: 60, maxAge: 100 },
  ],

  article_categories: named(
    ["تمرین", "TRAINING"],
    ["تغذیه", "NUTRITION"],
    ["سلامت", "HEALTH"],
    ["اخبار", "NEWS"],
    ["ریکاوری", "RECOVERY"],
    ["روان‌شناسی ورزش", "SPORT_PSYCHOLOGY"],
    ["پیشگیری از آسیب", "INJURY_PREVENTION"],
  ),
  article_types: named(
    ["مقاله آموزشی", "EDUCATIONAL"],
    ["راهنما", "GUIDE"],
    ["خبر", "NEWS"],
    ["مصاحبه", "INTERVIEW"],
    ["برنامه تمرینی", "WORKOUT_PROGRAM"],
    ["پرسش و پاسخ", "Q_AND_A"],
  ),
  article_tags: named(
    ["بدنسازی", "BODYBUILDING"],
    ["تغذیه سالم", "HEALTHY_NUTRITION"],
    ["سبک زندگی", "LIFESTYLE"],
    ["کاهش وزن", "WEIGHT_LOSS"],
    ["تمرین در خانه", "HOME_WORKOUT"],
    ["ریکاوری", "RECOVERY"],
    ["ورزش بانوان", "WOMEN_SPORT"],
    ["ورزش کودکان", "KIDS_SPORT"],
    ["دویدن", "RUNNING"],
    ["یوگا", "YOGA"],
  ),
  faq_categories: named(
    ["عضویت", "MEMBERSHIP"],
    ["رزرو کلاس", "BOOKING"],
    ["پرداخت", "PAYMENT"],
    ["باشگاه‌ها", "CLUBS"],
    ["مربی‌ها", "COACHES"],
    ["حساب کاربری", "ACCOUNT"],
    ["لغو و بازپرداخت", "CANCELLATION_REFUND"],
  ),
  page_types: named(
    ["صفحه ثابت", "STATIC"],
    ["صفحه فرود", "LANDING"],
    ["صفحه کمپین", "CAMPAIGN"],
  ),
  banner_types: named(
    ["تصویری", "IMAGE"],
    ["متنی", "TEXT"],
    ["ویدیویی", "VIDEO"],
  ),
  banner_positions: named(
    ["بالای صفحه", "HERO"],
    ["میان محتوا", "INLINE"],
    ["پایین صفحه", "FOOTER"],
  ),
  notification_categories: named(
    ["رزرو", "BOOKING"],
    ["پرداخت", "PAYMENT"],
    ["یادآوری", "REMINDER"],
    ["سیستمی", "SYSTEM"],
    ["عضویت", "MEMBERSHIP"],
    ["کلاس و مربی", "CLASS_COACH"],
    ["پشتیبانی", "SUPPORT"],
    ["تخفیف و پیشنهاد", "PROMOTION"],
  ),
  featured_collection_types: named(
    ["باشگاه‌های منتخب", "FEATURED_CLUBS"],
    ["کلاس‌های محبوب", "POPULAR_CLASSES"],
    ["مربیان برتر", "TOP_COACHES"],
    ["باشگاه‌های نزدیک", "NEARBY_CLUBS"],
    ["کلاس‌های تازه", "NEW_CLASSES"],
    ["پیشنهادهای اقتصادی", "BEST_VALUE"],
  ),

  verification_document_types: named(
    ["کارت ملی", "NATIONAL_ID"],
    ["مدرک مربیگری", "COACH_CERTIFICATE"],
    ["مجوز فعالیت", "BUSINESS_LICENSE"],
    ["کارت بیمه ورزشی", "SPORT_INSURANCE"],
    ["گواهی سلامت", "HEALTH_CERTIFICATE"],
    ["سند محل فعالیت", "VENUE_DOCUMENT"],
  ),
  club_rejection_reasons: named(
    ["مدارک ناقص", "INCOMPLETE_DOCUMENTS"],
    ["اطلاعات تماس نامعتبر", "INVALID_CONTACT"],
    ["عدم تطابق مجوز", "LICENSE_MISMATCH"],
    ["تصاویر نامناسب یا ناکافی", "INVALID_MEDIA"],
    ["آدرس قابل تأیید نیست", "UNVERIFIED_ADDRESS"],
    ["اطلاعات امکانات نادرست", "INVALID_FACILITIES"],
    ["عدم رعایت استاندارد ایمنی", "SAFETY_NON_COMPLIANCE"],
  ),
  coach_rejection_reasons: named(
    ["مدرک نامعتبر", "INVALID_CERTIFICATE"],
    ["سابقه ناکافی", "INSUFFICIENT_EXPERIENCE"],
    ["اطلاعات ناقص", "INCOMPLETE_PROFILE"],
    ["تصویر پروفایل نامناسب", "INVALID_PROFILE_IMAGE"],
    ["تخصص قابل تأیید نیست", "UNVERIFIED_SPECIALTY"],
    ["مغایرت اطلاعات هویتی", "IDENTITY_MISMATCH"],
  ),
  report_reasons: named(
    ["اطلاعات نادرست", "FALSE_INFORMATION"],
    ["محتوای نامناسب", "INAPPROPRIATE_CONTENT"],
    ["رفتار توهین‌آمیز", "ABUSIVE_BEHAVIOR"],
    ["قیمت‌گذاری گمراه‌کننده", "MISLEADING_PRICE"],
    ["عدم تطابق خدمت", "SERVICE_MISMATCH"],
    ["مسئله ایمنی یا بهداشت", "SAFETY_HYGIENE"],
    ["حساب یا آگهی تکراری", "DUPLICATE"],
    ["کلاهبرداری یا سوءاستفاده", "FRAUD"],
  ),
  review_report_reasons: named(
    ["نظر اسپم", "SPAM"],
    ["توهین‌آمیز", "ABUSIVE"],
    ["نامرتبط", "IRRELEVANT"],
    ["اطلاعات شخصی", "PERSONAL_INFORMATION"],
    ["ادعای نادرست", "FALSE_CLAIM"],
    ["تبلیغ رقبا", "COMPETITOR_PROMOTION"],
  ),
  suspension_reasons: named(
    ["نقض قوانین", "POLICY_VIOLATION"],
    ["مدارک منقضی", "EXPIRED_DOCUMENTS"],
    ["فعالیت مشکوک", "SUSPICIOUS_ACTIVITY"],
    ["شکایت‌های تأییدشده متعدد", "REPEATED_COMPLAINTS"],
    ["تسویه مالی ناموفق", "PAYMENT_DEFAULT"],
    ["عدم رعایت الزامات ایمنی", "SAFETY_VIOLATION"],
  ),
  support_ticket_categories: named(
    ["مشکل فنی", "TECHNICAL"],
    ["حساب کاربری", "ACCOUNT"],
    ["رزرو و کلاس", "BOOKING"],
    ["امور مالی", "FINANCE"],
    ["باشگاه و امکانات", "CLUB_FACILITIES"],
    ["مربی و خدمات", "COACH_SERVICES"],
    ["لغو و بازپرداخت", "CANCELLATION_REFUND"],
    ["احراز هویت", "VERIFICATION"],
    ["پیشنهاد و انتقاد", "FEEDBACK"],
  ),

  badge_types: [
    { name: "تأییدشده", code: "VERIFIED", color: "#2563EB" },
    { name: "مربی برتر", code: "TOP_COACH", color: "#F59E0B" },
    { name: "باشگاه محبوب", code: "POPULAR_CLUB", color: "#10B981" },
    { name: "پاسخ‌گویی سریع", code: "FAST_RESPONSE", color: "#8B5CF6" },
    { name: "انتخاب اقتصادی", code: "BEST_VALUE", color: "#0EA5E9" },
    { name: "تازه‌وارد", code: "NEWCOMER", color: "#EC4899" },
    { name: "امکانات کامل", code: "FULLY_EQUIPPED", color: "#14B8A6" },
  ],
  featured_collections: [
    {
      title: "باشگاه‌های منتخب تهران",
      typeId: "@FEATURED_CLUBS",
      entityType: "club",
      itemIds: [],
    },
    {
      title: "کلاس‌های محبوب این هفته",
      typeId: "@POPULAR_CLASSES",
      entityType: "class",
      itemIds: [],
    },
  ],
  search_keywords: named(
    ["باشگاه بدنسازی", "GYM"],
    ["کلاس فیتنس", "FITNESS_CLASS"],
    ["مربی خصوصی", "PERSONAL_COACH"],
    ["کلاس یوگا", "YOGA_CLASS"],
    ["استخر نزدیک من", "NEARBY_POOL"],
    ["زمین فوتبال", "FOOTBALL_FIELD"],
    ["کلاس پیلاتس", "PILATES_CLASS"],
    ["باشگاه بانوان", "WOMEN_GYM"],
    ["مربی آنلاین", "ONLINE_COACH"],
    ["کلاس کودکان", "KIDS_CLASS"],
  ),
  search_synonyms: [
    { canonicalTerm: "باشگاه", synonyms: ["جیم", "سالن ورزشی"] },
    { canonicalTerm: "بدنسازی", synonyms: ["فیتنس", "پرورش اندام"] },
    { canonicalTerm: "مربی خصوصی", synonyms: ["پرسونال ترینر", "PT"] },
    { canonicalTerm: "تنیس روی میز", synonyms: ["پینگ‌پنگ", "پینگ پنگ"] },
    {
      canonicalTerm: "تمرین عملکردی",
      synonyms: ["فانکشنال", "تمرین فانکشنال"],
    },
    { canonicalTerm: "تمرینات تعلیقی", synonyms: ["TRX", "تی آر ایکس"] },
    { canonicalTerm: "دویدن", synonyms: ["رانینگ", "تمرین دو"] },
    { canonicalTerm: "استخر", synonyms: ["مجموعه آبی", "شنا"] },
  ],
  popular_searches: [
    { phrase: "باشگاه بدنسازی تهران", weight: 100, cityId: "@TEHRAN_CITY" },
    { phrase: "مربی خصوصی", weight: 80, cityId: "@TEHRAN_CITY" },
    { phrase: "کلاس یوگا تهران", weight: 75, cityId: "@TEHRAN_CITY" },
    { phrase: "استخر کرج", weight: 70, cityId: "@KARAJ" },
    { phrase: "باشگاه بدنسازی مشهد", weight: 68, cityId: "@MASHHAD" },
    { phrase: "کلاس پیلاتس اصفهان", weight: 62, cityId: "@ISFAHAN_CITY" },
    { phrase: "زمین فوتبال شیراز", weight: 58, cityId: "@SHIRAZ" },
    { phrase: "مربی بدنسازی تبریز", weight: 55, cityId: "@TABRIZ" },
  ],
  discovery_sections: [
    {
      title: "باشگاه‌های منتخب",
      code: "FEATURED_CLUBS",
      entityType: "club",
      collectionId: "@باشگاه‌های منتخب تهران",
      placement: "home",
      displayLimit: 10,
    },
    {
      title: "کلاس‌های محبوب",
      code: "POPULAR_CLASSES",
      entityType: "class",
      collectionId: "@کلاس‌های محبوب این هفته",
      placement: "home",
      displayLimit: 10,
    },
  ],

  membership_plan_types: named(
    ["عضویت جلسه‌ای", "PAY_AS_YOU_GO"],
    ["بسته چندجلسه‌ای", "SESSION_PACK"],
    ["عضویت ماهانه", "MONTHLY"],
    ["عضویت فصلی", "QUARTERLY"],
    ["عضویت شش‌ماهه", "SEMI_ANNUAL"],
    ["عضویت سالانه", "ANNUAL"],
  ),
  pricing_models: [
    { name: "به‌ازای جلسه", code: "PER_SESSION", billingUnit: "session" },
    { name: "اشتراک ثابت", code: "SUBSCRIPTION", billingUnit: "period" },
    {
      name: "به‌ازای نفر",
      code: "PER_PARTICIPANT",
      billingUnit: "participant",
    },
    { name: "به‌ازای ساعت", code: "PER_HOUR", billingUnit: "hour" },
    { name: "بسته جلسات", code: "SESSION_PACKAGE", billingUnit: "package" },
  ],
  subscription_periods: [
    { name: "یک‌هفته‌ای", durationValue: 1, durationUnit: "week" },
    { name: "یک‌ماهه", durationValue: 1, durationUnit: "month" },
    { name: "سه‌ماهه", durationValue: 3, durationUnit: "month" },
    { name: "شش‌ماهه", durationValue: 6, durationUnit: "month" },
    { name: "یک‌ساله", durationValue: 1, durationUnit: "year" },
  ],
  cancellation_reasons: named(
    ["تغییر برنامه زمانی", "SCHEDULE_CHANGE"],
    ["بیماری یا آسیب‌دیدگی", "HEALTH_ISSUE"],
    ["شرایط اضطراری خانوادگی", "FAMILY_EMERGENCY"],
    ["مشکل رفت‌وآمد", "TRANSPORTATION_ISSUE"],
    ["شرایط نامساعد جوی", "WEATHER_CONDITION"],
    ["سفر غیرمنتظره", "UNEXPECTED_TRAVEL"],
    ["رزرو اشتباه", "BOOKED_BY_MISTAKE"],
    ["رزرو تکراری", "DUPLICATE_BOOKING"],
    ["انتخاب سانس نامناسب", "WRONG_TIME_SLOT"],
    ["تغییر مربی یا کلاس", "COACH_OR_CLASS_CHANGED"],
    ["لغو توسط باشگاه", "CLUB_CANCELLED"],
    ["عدم حضور یا تأخیر مربی", "COACH_UNAVAILABLE"],
    ["کیفیت نامناسب امکانات", "FACILITY_ISSUE"],
    ["عدم رضایت", "DISSATISFIED"],
    ["سایر دلایل", "OTHER"],
  ),
  discount_categories: named(
    ["کاربر جدید", "NEW_USER"],
    ["مناسبتی", "SEASONAL"],
    ["وفاداری", "LOYALTY"],
    ["معرفی دوستان", "REFERRAL"],
    ["خرید گروهی", "GROUP_BOOKING"],
    ["رزرو کم‌تقاضا", "OFF_PEAK"],
    ["دانشجویی", "STUDENT"],
    ["سازمانی", "CORPORATE"],
  ),
  invoice_item_types: named(
    ["هزینه عضویت", "MEMBERSHIP"],
    ["رزرو کلاس", "CLASS_BOOKING"],
    ["خدمات مربی", "COACH_SERVICE"],
    ["رزرو زمین یا سالن", "COURT_BOOKING"],
    ["اجاره تجهیزات", "EQUIPMENT_RENTAL"],
    ["خدمات جانبی", "ADD_ON_SERVICE"],
    ["مالیات و عوارض", "TAX"],
    ["تخفیف", "DISCOUNT"],
  ),
  refund_reasons: named(
    ["لغو توسط باشگاه", "CLUB_CANCELLED"],
    ["لغو توسط مربی", "COACH_CANCELLED"],
    ["لغو مطابق سیاست بازپرداخت", "POLICY_CANCELLATION"],
    ["کیفیت نامناسب خدمت", "SERVICE_QUALITY"],
    ["خدمت ارائه نشد", "SERVICE_NOT_DELIVERED"],
    ["پرداخت تکراری", "DUPLICATE_PAYMENT"],
    ["مبلغ اشتباه", "INCORRECT_AMOUNT"],
    ["خطای سیستمی", "SYSTEM_ERROR"],
    ["رویداد خارج از کنترل", "FORCE_MAJEURE"],
  ),
};
