import type { DiscoverySectionLayout } from "./discovery-placeholder-sections";

// Initial layout mirrors the server defaults; subsequent loads use the last received feed layout.
export const defaultDiscoveryLayouts: DiscoverySectionLayout[] = [
  {
    id: "featured-banners",
    key: "featured-banners",
    type: "banners",
    skeletonCount: 2,
    title: "پیشنهادهای ویژه",
    subtitle: "فرصت‌های تازه برای شروع حرکت",
    layout: "16/9:1",
    position: 0,
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "top-rated-clubs",
    key: "top-rated-clubs",
    type: "clubs",
    title: "باشگاه‌های محبوب",
    subtitle: "انتخاب کاربران جیم‌فورمی",
    layout: "editorial",
    position: 1,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/clubs",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "featured-coaches",
    key: "featured-coaches",
    type: "coaches",
    title: "مربی‌های منتخب",
    subtitle: "کنار حرفه‌ای‌ها به هدفت برس",
    layout: "carousel",
    position: 2,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "featured-classes",
    key: "featured-classes",
    type: "classes",
    title: "کلاس‌های پیشنهادی",
    subtitle: "کلاس‌های فعال و آماده ثبت‌نام",
    layout: "carousel",
    position: 3,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/classes",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "latest-articles",
    key: "latest-articles",
    type: "articles",
    title: "تازه‌های مجله",
    subtitle: "تمرین بهتر، تغذیه سالم‌تر و زندگی فعال‌تر",
    layout: "carousel",
    position: 4,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/articles",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "new-coaches",
    key: "new-coaches",
    type: "coaches",
    title: "مربی‌های تازه‌وارد",
    subtitle: "با چهره‌های تازه دنیای ورزش آشنا شو",
    layout: "compact",
    position: 5,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "article-library",
    key: "article-library",
    type: "articles",
    title: "مطالب منتخب برای تو",
    subtitle: "راهنماهای کاربردی برای تمرین و سبک زندگی سالم",
    layout: "horizontal-outline",
    position: 6,
    viewAllLabel: "همه مقاله‌ها",
    viewAllUrl: "/discovery/articles",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "discovery-guides",
    key: "discovery-guides",
    type: "banners",
    skeletonCount: 2,
    title: "از کجا شروع کنم؟",
    subtitle: "مسیرهای سریع برای رسیدن به انتخاب مناسب",
    layout: "16/9:1.2",
    position: 7,
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "discovery-quick-paths",
    key: "discovery-quick-paths",
    type: "banners",
    skeletonCount: 3,
    title: "انتخاب سریع",
    subtitle: "راه‌های کوتاه‌تر برای پیدا کردن گزینه مناسب",
    layout: "4/3:auto",
    position: 8,
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "#18f47b",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "discovery-stories",
    key: "discovery-stories",
    type: "banners",
    skeletonCount: 3,
    title: "پیشنهادهای امروز",
    subtitle: "کارت‌های عمودی برای کشف سریع‌تر",
    layout: "3/4:auto",
    position: 9,
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "center",
      viewAllVariant: "link",
    },
  },
  {
    id: "popular-sports",
    key: "popular-sports",
    type: "sports",
    title: "رشته‌های محبوب",
    subtitle: "ورزش مناسب هدفت را پیدا کن",
    layout: "carousel",
    position: 10,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "ball-sports",
    key: "ball-sports",
    type: "sports",
    title: "ورزش‌های توپی",
    subtitle: "از فوتبال و والیبال تا بسکتبال",
    layout: "carousel",
    position: 11,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "mind-body-sports",
    key: "mind-body-sports",
    type: "sports",
    title: "ذهن و بدن",
    subtitle: "یوگا، پیلاتس و تمرین‌های آرامش‌بخش",
    layout: "carousel",
    position: 12,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "online-coaches",
    key: "online-coaches",
    type: "coaches",
    title: "مربی‌های آنلاین",
    subtitle: "هرجا هستی با مربی حرفه‌ای تمرین کن",
    layout: "compact",
    position: 13,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
  {
    id: "discovery-portrait-stories",
    key: "discovery-portrait-stories",
    type: "banners",
    skeletonCount: 3,
    title: "داستان‌های ورزشی",
    subtitle: "پیشنهادهای کوتاه برای شروع یک تجربه تازه",
    layout: "9/16:auto",
    position: 14,
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: {
      backgroundColor: "transparent",
      textColor: "",
      accentColor: "",
      showHeader: true,
      showViewAll: true,
      headerAlignment: "start",
      viewAllVariant: "link",
    },
  },
];
