/* Generated by scripts/build-icons.mjs — do not edit. */

export const iconNames = [
  "academic-cap",
  "acorn",
  "acupuncture",
  "airplane",
  "alarm",
  "alcohol-1",
  "alcohol-2",
  "align-bottom-1",
  "align-bottom-2",
  "align-center-horizontal-1",
  "align-center-horizontal-2",
  "align-center-vertical-1",
  "align-center-vertical-2",
  "align-left-1",
  "align-left-2",
  "align-right-1",
  "align-right-2",
  "align-top-1",
  "align-top-2",
  "anchor",
  "antibody",
  "apple",
  "archery",
  "archive",
  "arow-shuffle",
  "arrow-backward-1",
  "arrow-backward-2",
  "arrow-bend-down-left-1",
  "arrow-bend-down-left-2",
  "arrow-bend-down-right-1",
  "arrow-bend-down-right-2",
  "arrow-bend-up-left-1",
  "arrow-bend-up-left-2",
  "arrow-bend-up-right-1",
  "arrow-bend-up-right-2",
  "arrow-down-circle",
  "arrow-down-left-circle",
  "arrow-down-left",
  "arrow-down-right-circle",
  "arrow-down-right",
  "arrow-down-up",
  "arrow-down",
  "arrow-fat-down",
  "arrow-fat-left",
  "arrow-fat-right",
  "arrow-fat-up",
  "arrow-forward-1",
  "arrow-forward-2",
  "arrow-horizontal",
  "arrow-left-circle",
  "arrow-left-right",
  "arrow-left",
  "arrow-line-down",
  "arrow-line-left",
  "arrow-line-right",
  "arrow-line-up",
  "arrow-maximize",
  "arrow-minimize",
  "arrow-omnidirectional-inside-1",
  "arrow-omnidirectional-inside-2",
  "arrow-omnidirectional-outside-1",
  "arrow-omnidirectional-outside-2",
  "arrow-recycle",
  "arrow-redo",
  "arrow-repeat-clockwise-1",
  "arrow-repeat-clockwise-2",
  "arrow-repeat-counterclockwise-1",
  "arrow-repeat-counterclockwise-2",
  "arrow-reply",
  "arrow-right-circle",
  "arrow-right",
  "arrow-rotate-clockwise-1",
  "arrow-rotate-counterclockwise-1",
  "arrow-share",
  "arrow-sign-in-1",
  "arrow-sign-in-2",
  "arrow-sign-out-1",
  "arrow-sign-out-2",
  "arrow-skip-backward",
  "arrow-skip-forward",
  "arrow-split",
  "arrow-square-in",
  "arrow-square-out",
  "arrow-top-left",
  "arrow-trend-down",
  "arrow-trend-up",
  "arrow-undo",
  "arrow-up-circle",
  "arrow-up-left-circle",
  "arrow-up-right-circle",
  "arrow-up-right",
  "arrow-up",
  "arrow-upload-1",
  "arrow-upload",
  "arrow-vector-three",
  "arrow-vector-two",
  "arrow-vertical",
  "asthma-inhaler",
  "atom",
  "avocado",
  "baby-bottle-1",
  "baby-bottle-2",
  "baby-crib",
  "baby-face-1",
  "baby-face-2",
  "baby-face-3",
  "baby-face-4",
  "baby-stroll",
  "baby-wrap",
  "backspace",
  "bacteria-1",
  "bacteria-11",
  "bacteria",
  "balance",
  "banana",
  "bandaid",
  "bandaids",
  "bank-1",
  "bank-2",
  "barbell-diagonal",
  "barbell-horizontal",
  "baseball-bat",
  "baseball-helmet",
  "baseball",
  "basketball",
  "battery-empty",
  "battery-full",
  "battery-high",
  "battery-low",
  "battery-medium",
  "bed",
  "bell-1",
  "bell-2",
  "bell-3",
  "bell-4",
  "bell-ringing",
  "bell-slash-1",
  "bell-slash-2",
  "bell-slash-3",
  "bell-slash-4",
  "bicep",
  "bicycle",
  "bill-medical",
  "bill",
  "binocular",
  "biohazard",
  "blender-1",
  "blender-2",
  "blood-cells-1",
  "blood-cells-2",
  "blood-cells-circulation",
  "bluetooth-active",
  "bluetooth-slash",
  "bluetooth",
  "boat",
  "body-fat",
  "body-lotion",
  "body-wash",
  "bone-crack",
  "bone",
  "book-closed",
  "book-open",
  "bookmark",
  "bookmarks",
  "bowl-of-hygeia-1",
  "bowl-of-hygeia-2",
  "box-cube",
  "boxing",
  "brackets-curly",
  "brackets-round",
  "brackets-sharp",
  "brackets-square",
  "brain-1",
  "brain-2",
  "bread-toast",
  "briefcase-1",
  "briefcase-2",
  "briefcase-plus",
  "broccoli",
  "browser",
  "bug",
  "building-1",
  "building-2",
  "building-3",
  "building-4",
  "bus",
  "cake",
  "calendar-1",
  "calendar-2",
  "calendar-check",
  "calendar-heart",
  "calendar-minus",
  "calendar-plus",
  "calendar-slash-1",
  "calendar-slash-2",
  "camera-1",
  "camera-2",
  "camera-slash-1",
  "camera-slash-2",
  "cancer-cell-1",
  "cancer-cell-2",
  "cancer-ribbon",
  "cannabis",
  "car-1",
  "car-2",
  "car-van",
  "carrot",
  "celebration",
  "cell",
  "cells",
  "chart-area",
  "chart-axis-area",
  "chart-axis-bar-1",
  "chart-axis-bar-2",
  "chart-axis-bar-3",
  "chart-axis-bar-stacked-1",
  "chart-axis-bar-stacked-2",
  "chart-axis-bubble",
  "chart-axis-line-sharp",
  "chart-axis-line-wave",
  "chart-axis-lines",
  "chart-axis-node",
  "chart-axis-scatter",
  "chart-bar-1",
  "chart-bar-2",
  "chart-bar-3",
  "chart-bar-fat-1",
  "chart-bar-fat-2",
  "chart-bar-fat-3",
  "chart-bar-stacked",
  "chart-bubble",
  "chart-candlestick-1",
  "chart-candlestick-2",
  "chart-decision-tree-1",
  "chart-decision-tree-2",
  "chart-decision-tree-3",
  "chart-donut-1",
  "chart-donut-2",
  "chart-node-1",
  "chart-node-2",
  "chart-pie-1",
  "chart-pie-2",
  "chart-pie-3",
  "chart-pie-4",
  "chart-sankey",
  "chart-trend-down",
  "chart-trend-up",
  "chart-waterfall-1",
  "chart-waterfall-2",
  "chat-dot",
  "chat-line",
  "chat-slash",
  "chat-smile",
  "chat",
  "check-circle",
  "check",
  "checks-1",
  "checks-2",
  "chef-hat",
  "cherry",
  "chevron-double-down-circle",
  "chevron-double-down",
  "chevron-double-left-circle",
  "chevron-double-left",
  "chevron-double-right-circle",
  "chevron-double-right",
  "chevron-double-up-circle",
  "chevron-double-up",
  "chevron-down-circle",
  "chevron-down-up",
  "chevron-down",
  "chevron-fat-down",
  "chevron-fat-left",
  "chevron-fat-right",
  "chevron-fat-up",
  "chevron-left-circle",
  "chevron-left-right",
  "chevron-left",
  "chevron-right-circle",
  "chevron-right-left",
  "chevron-right",
  "chevron-up-circle",
  "chevron-up-down",
  "chevron-up",
  "chicken-drumstick",
  "chromosome-xx",
  "chromosome-xy",
  "cigarette-slash",
  "cigarette",
  "clipboard",
  "clock",
  "close-x-circle",
  "close-x",
  "cloud-1",
  "cloud-2",
  "cloud-download-1",
  "cloud-download-2",
  "cloud-fog",
  "cloud-rain-1",
  "cloud-rain",
  "cloud-slash-1",
  "cloud-slash-2",
  "cloud-snow",
  "cloud-sun",
  "cloud-thunder",
  "cloud-upload-1",
  "cloud-upload-2",
  "coffee",
  "column-item",
  "column-three",
  "column-two",
  "command-key",
  "compass",
  "condom",
  "contact-book",
  "cookie",
  "cooking-pot",
  "copy-1",
  "copy-2",
  "corn",
  "credit-card",
  "cricket",
  "crispr",
  "croissant",
  "crown-1",
  "crown-2",
  "crutches",
  "currecy-try",
  "currency-btc",
  "currency-chf",
  "currency-cny",
  "currency-eth",
  "currency-eur",
  "currency-gbp",
  "currency-ils",
  "currency-inr",
  "currency-jpy",
  "currency-krw",
  "currency-rub",
  "currency-usd",
  "cursor-1",
  "cursor-2",
  "cursor-text",
  "dashboard",
  "database",
  "dental-equipment",
  "dermatoscope",
  "diamond-1",
  "diamond-2",
  "divide",
  "dna",
  "document-fold",
  "door",
  "dot-nine",
  "dot-six-horizontal",
  "dot-six-vertical",
  "dot-three-horizontal",
  "dot-three-vertical",
  "dragger",
  "drone-1",
  "drone-2",
  "drug-container-1",
  "drug-container-2",
  "drug-powder",
  "drug-store",
  "ear-1",
  "ear-2",
  "earphone-case",
  "earphone-left",
  "earphone-right",
  "earphones",
  "ecg-vital-sign",
  "egg-cracked",
  "egg-1",
  "egg-2",
  "egg-3",
  "elbow",
  "email-at",
  "emergency",
  "emotion-depressed",
  "emotion-happy",
  "emotion-nervous",
  "emotion-neutral",
  "emotion-overjoyed",
  "emotion-sad",
  "emotion-unhappy",
  "enema",
  "envelope-1",
  "envelope-2",
  "envelope-open-1",
  "envelope-open-2",
  "equal-approximate",
  "equal",
  "equalizer",
  "exclamation-mark-circle",
  "exclamation-mark-triangle",
  "exclamation-mark",
  "eye-closed",
  "eye-retina",
  "eye-slash",
  "eye-water-drop",
  "eye",
  "eyedropper",
  "face-depressed",
  "face-happy",
  "face-id",
  "face-mask-1-1",
  "face-mask-1",
  "face-mask-2",
  "face-neutral",
  "face-overjoyed",
  "face-sad",
  "fast-food",
  "feces",
  "female-waist-genital",
  "female-waist-heart",
  "female-waist-underwear",
  "fetus",
  "file-1",
  "file-2",
  "file-archive",
  "file-check",
  "file-download",
  "file-lab-test",
  "file-magnifying-glass",
  "file-minus",
  "file-plus",
  "file-upload",
  "file-x",
  "film-strip",
  "fingerprint-1",
  "fingerprint-2",
  "fire-1",
  "fire-2",
  "fire-truck",
  "fish",
  "fitness-bike-1",
  "fitness-bike-2",
  "fitness-bike-3",
  "flag-1",
  "flag-2",
  "flashlight",
  "flask-circle",
  "flask-triangle",
  "floppy-disk-1",
  "floppy-disk-2",
  "flower-fertile",
  "folder-archive",
  "folder-open",
  "folder",
  "foot-step",
  "foot-steps",
  "foot",
  "forbidden-circle",
  "forbidden-square",
  "fork-knife",
  "fork-spoon",
  "four-diamonds",
  "funnel-1",
  "funnel-2",
  "funnel-3",
  "funnel-4",
  "game-controller",
  "garlic",
  "gauge-1",
  "gauge-2",
  "gavel-1",
  "gavel-2",
  "gear-1",
  "gear-2",
  "gender-female",
  "gender-male",
  "gender-transgender",
  "gift",
  "globe",
  "glucose",
  "golf",
  "grapefruit",
  "grid-four",
  "grid-nine",
  "hair-brush",
  "hair-comb-1",
  "hair-comb-2",
  "hamburger",
  "hammer",
  "hand-coin",
  "hand-grip",
  "hand-health-cross",
  "hand-heart",
  "hand-massage",
  "hand-mirror",
  "hand-pan",
  "hand-pill",
  "hand-pointing",
  "hand-skeleton",
  "hand-stop",
  "hand-swipe-left",
  "hand-swipe-right",
  "hand-touch",
  "hand-wash-1",
  "hand-wash-2",
  "hand",
  "hands-health-cross",
  "handshake",
  "hard-drive",
  "hash-tag-1",
  "hash-tag-2",
  "head-acupuncture",
  "head-cognition",
  "head-ent",
  "head-plus",
  "head-sneeze",
  "head-spiral",
  "head",
  "headphone-1",
  "headphone-2",
  "headset-1",
  "headset-2",
  "health-cross-1",
  "health-cross-2",
  "health-cross-3",
  "hearing-aid-1",
  "hearing-aid-2",
  "heart-1",
  "heart-broken",
  "heart-check",
  "heart-ecg",
  "heart-wellness-1",
  "heart-wellness-2",
  "heart",
  "helicopter",
  "hockey",
  "hospital-h",
  "hospital",
  "hourglass-1",
  "hourglass-2",
  "house-1",
  "house-2",
  "house-3",
  "ice-cream",
  "ice-skating",
  "identity-card-1",
  "identity-card-2",
  "image-1",
  "image-2",
  "info-circle",
  "info",
  "intestine-1",
  "intestine-2",
  "invoice",
  "iv-bag-1",
  "iv-bag-2",
  "jumping-rope",
  "kebab",
  "kettlebell",
  "key-1",
  "key-2",
  "keyboard-1",
  "keyboard-2",
  "keyboard-3",
  "kidney",
  "kidneys-2",
  "kidneys",
  "knee",
  "knife",
  "landscape",
  "laptop-mobile",
  "laptop",
  "layer-three",
  "layer-two",
  "leaf",
  "leaves-1",
  "leaves-2",
  "letter-a-circle",
  "letter-a",
  "letter-b-circle",
  "letter-b",
  "letter-c-circle",
  "letter-c",
  "letter-d-circle",
  "letter-d",
  "letter-e-circle",
  "letter-e",
  "letter-f-circle",
  "letter-f",
  "letter-g-circle",
  "letter-g",
  "letter-h-circle",
  "letter-h",
  "letter-i-circle",
  "letter-i",
  "letter-j-circle",
  "letter-j",
  "letter-k-circle",
  "letter-k",
  "letter-l-circle",
  "letter-l",
  "letter-m-circle",
  "letter-m",
  "letter-n-circle",
  "letter-n",
  "letter-o-circle",
  "letter-o",
  "letter-p-circle",
  "letter-p",
  "letter-q-circle",
  "letter-q",
  "letter-r-circle",
  "letter-r",
  "letter-s-circle",
  "letter-s",
  "letter-t-circle",
  "letter-t",
  "letter-u-circle",
  "letter-u",
  "letter-v-circle",
  "letter-v",
  "letter-w-circle",
  "letter-w",
  "letter-x-circle",
  "letter-x",
  "letter-y-circle",
  "letter-y",
  "letter-z-circle",
  "letter-z",
  "lifebuoy",
  "light-bulb-1-active",
  "light-bulb-1",
  "light-bulb-2-active",
  "light-bulb-2",
  "lightning-bolt-1",
  "lightning-bolt-2",
  "lightning-bolt-3",
  "lightning-bolt-slash-1",
  "lightning-bolt-slash-2",
  "lightning-bolt-slash-3",
  "link-1",
  "link-2",
  "link-3",
  "link-4",
  "link-break-1",
  "link-break-2",
  "lipstick",
  "list-three-bullet",
  "list-three-check",
  "list-three-square",
  "list-two-bullet",
  "list-two-check",
  "list-two-square",
  "liver-1",
  "liver-2",
  "lock-1",
  "lock-2",
  "lock-unlocked-1",
  "lock-unlocked-2",
  "lung",
  "magnet",
  "magnifying-glass-minus",
  "magnifying-glass-plus",
  "magnifying-glass",
  "mailbox",
  "makeup-brush",
  "map-pin-1",
  "map-pin-2",
  "map-pin-3",
  "map-pin-4",
  "map-street",
  "map-trifold",
  "margin",
  "mascara",
  "mask-happy-sad",
  "mask-happy",
  "mask-sad",
  "massage-acupuncture",
  "maximize",
  "measuring-tape",
  "medal",
  "medical-card-1",
  "medical-card-2",
  "medical-oral-device",
  "medical-scissor",
  "medical-tweezer",
  "megaphone",
  "menstrual-pad",
  "menu-center",
  "menu-grid-1",
  "menu-left",
  "menu-right",
  "microphone-slash",
  "microphone",
  "microscope-1",
  "microscope-2",
  "milk-carton",
  "minimize",
  "minus-circle",
  "minus-fat-circle",
  "minus-fat",
  "minus",
  "mobile",
  "molecule-1",
  "molecule-2",
  "molecule-honeycomb",
  "molecules",
  "monitor",
  "moon",
  "moped",
  "mortar-and-pestle-1",
  "mortar-and-pestle-2",
  "motorcycle",
  "mouse-1",
  "mouse-2",
  "mouse",
  "mouth-wash",
  "music-note-1",
  "music-note-2",
  "nail-polish",
  "newspaper-1",
  "newspaper-2",
  "nose",
  "notches",
  "note-1",
  "note-2",
  "note-pencil",
  "number-binary",
  "number-eight-circle",
  "number-eight",
  "number-five-circle",
  "number-five",
  "number-four-circle",
  "number-four",
  "number-nine-circle",
  "number-nine",
  "number-one-circle",
  "number-one",
  "number-seven-circle",
  "number-seven",
  "number-six-circle",
  "number-six",
  "number-three-circle",
  "number-three",
  "number-two-circle",
  "number-two",
  "number-zero-circle",
  "number-zero",
  "nurse-hat",
  "option-key",
  "orange",
  "otoscope",
  "ovarium-1",
  "ovarium-2",
  "oven",
  "oxygen-tank",
  "padding",
  "palette",
  "paper-clip-1",
  "paper-clip-2",
  "paper-money",
  "paper-plane-diagonal",
  "paper-plane-horizontal",
  "paper-plane-vertical",
  "passport",
  "path-1",
  "path-2",
  "pause-circle",
  "pause",
  "paw",
  "peanut",
  "pen",
  "pencil-1",
  "pencil-2",
  "pencil-line-1",
  "pencil-line-2",
  "percentage-circle",
  "percentage",
  "person-acrobatics",
  "person-arms-spread",
  "person-biking",
  "person-dodgeball",
  "person-elderly-female",
  "person-elderly-male",
  "person-hiking",
  "person-injured",
  "person-karate",
  "person-man-1",
  "person-man-2",
  "person-man-hands-up",
  "person-meditation",
  "person-pregnant-woman",
  "person-rowing",
  "person-running",
  "person-skating",
  "person-sleep-plus",
  "person-sleep",
  "person-soccer",
  "person-swimming",
  "person-walking",
  "person-wheelchair",
  "person-woman-1",
  "person-woman-2",
  "person-woman-hands-up",
  "person-yoga",
  "petri-dish-1",
  "petri-dish-2",
  "petri-dish-3",
  "petri-dish-4",
  "piggy-bank",
  "pill-circle",
  "pill-diamond",
  "pill-hexagon",
  "pill-oval",
  "pill-pentagon",
  "pill-ring",
  "pill-round-long",
  "pill-square-long",
  "pill-square",
  "pill-triangle",
  "pin-1",
  "pin-2",
  "pizza",
  "plant-pot",
  "play-circle",
  "play",
  "plus-circle",
  "plus-fat-circle",
  "plus-fat",
  "plus",
  "pollen",
  "power-cable",
  "power",
  "pregnancy-test",
  "prescription",
  "price-tag",
  "printer",
  "processor-cpu",
  "psychiatry",
  "puzzle",
  "qr-code",
  "question-mark-circle",
  "question-mark",
  "quotes",
  "radioactive",
  "ramen",
  "record-1",
  "record-2",
  "refrigerator",
  "ribcage",
  "rice-cooker",
  "rna",
  "robot-1",
  "robot-2",
  "robot-3",
  "robot-face-1",
  "robot-face-2",
  "robot-face-3",
  "rocket-diagonal-1",
  "rocket-diagonal-2",
  "rocket",
  "rod-of-asclepius",
  "roller-skating",
  "row-item",
  "row-three",
  "row-two",
  "rugby",
  "ruler-1",
  "ruler-2",
  "rx",
  "sanitizer",
  "scalpel",
  "scan-1",
  "scan-2",
  "scissors",
  "scooter",
  "seal-check",
  "server-1",
  "server-2",
  "shape-circle-half",
  "shape-circle",
  "shape-diamond",
  "shape-hexagon",
  "shape-pentagon",
  "shape-rectangle-1",
  "shape-rectangle-2",
  "shape-square",
  "shape-triangle",
  "shapes-triangle-square-circlce",
  "share-1",
  "share-2",
  "shield-check",
  "shield-exclamation-mark",
  "shield-plus",
  "shield-slash",
  "shield",
  "shopping-bag",
  "shopping-cart-1",
  "shopping-cart-2",
  "shower-1",
  "shower-2",
  "shrimp",
  "shuttlecock",
  "sidebar-left",
  "sidebar-right",
  "siren",
  "skillet",
  "skin-1",
  "skin-2",
  "skull",
  "sleep-zzz",
  "slider-dot-three-horizontal",
  "slider-dot-three-vertical",
  "slider-dot-two-horizontal",
  "slider-dot-two-vertical",
  "slider-line-three-horizontal",
  "slider-line-three-vertical",
  "slider-line-two-horizontal",
  "slider-line-two-vertical",
  "smart-watch-ekg",
  "smart-watch-plus",
  "smart-watch",
  "smile-depressed",
  "smile-happy",
  "smile-neutral",
  "smile-overjoyed",
  "smile-sad",
  "snowflake-1",
  "snowflake-2",
  "soccer-field",
  "soccer",
  "sort-ascending",
  "sort-descending",
  "soybean",
  "spanner",
  "sparkle-1",
  "sparkle-2",
  "sperm-2",
  "sperm",
  "spine-1",
  "spine",
  "squid",
  "star-circle",
  "star-four",
  "star-full",
  "star-half",
  "stem-cell-1",
  "stem-cell-2",
  "step-sneaker",
  "stethoscope-arrow-left",
  "stethoscope-arrow-right",
  "stethoscope-check",
  "stethoscope-mobile",
  "stethoscope",
  "stomach-1",
  "stomach",
  "stop-circle",
  "stop",
  "stopwatch",
  "storefront-1",
  "storefront-2",
  "strawberry",
  "sugar-bag",
  "sun",
  "syringe-1",
  "syringe-2",
  "table-mirror",
  "table",
  "tablet",
  "takeout-food",
  "tampon-1",
  "tampon-2",
  "target-1",
  "target-2",
  "teeth",
  "telephone-1",
  "telephone-2",
  "telephone-arrow-down-left-1",
  "telephone-arrow-down-left-2",
  "telephone-arrow-right-1",
  "telephone-arrow-right-2",
  "telephone-arrow-up-right-1",
  "telephone-arrow-up-right-2",
  "telephone-horizontal-1",
  "telephone-horizontal-2",
  "telephone-plus-1",
  "telephone-plus-2",
  "telephone-x-1",
  "telephone-x-2",
  "temperature-high",
  "temperature-low",
  "temperature-medium",
  "tennis-1",
  "tennis",
  "test-tube-1",
  "test-tube-2",
  "test-tube-3",
  "text-a",
  "text-align-center",
  "text-align-justified",
  "text-align-left",
  "text-align-right",
  "text-b",
  "text-columns",
  "text-field",
  "text-h",
  "text-i-italic",
  "text-indent",
  "text-outdent",
  "text-t",
  "text-u-underline",
  "thumbs-down",
  "thumbs-up",
  "ticket",
  "tie",
  "tilde",
  "toggle-left",
  "toggle-right",
  "tooth-brace",
  "tooth-crown",
  "tooth-floss",
  "tooth-implant",
  "tooth",
  "toothbrush-1",
  "toothbrush-2",
  "toothbrush-3",
  "torso-skeleton",
  "tounge",
  "tractor",
  "train-1",
  "train-2",
  "translate",
  "trash-1",
  "trash-2",
  "tray",
  "treadmill",
  "tree",
  "trophy-1",
  "trophy-2",
  "truck-ambulance",
  "truck-delivery",
  "truck",
  "tv",
  "tweezer",
  "umbrella",
  "user-check",
  "user-minus",
  "user-plus",
  "user-x",
  "user",
  "users-three",
  "users-two",
  "vaccine",
  "vibrate",
  "video-slash",
  "video",
  "virus-1",
  "virus-2",
  "volleyball",
  "volume-high",
  "volume-low",
  "volume-none",
  "volume-slash",
  "volume-x",
  "walking-aid",
  "wallet",
  "water-bottle-1",
  "water-bottle-2",
  "water-bottle-3",
  "water-drop-minus",
  "water-drop-plus",
  "water-drop",
  "water-glass-empty",
  "water-glass-high",
  "water-glass-low",
  "water-glass-medium",
  "wave-saw",
  "wave-sine",
  "wave-square",
  "wave",
  "weight-scale-minus",
  "weight-scale-plus",
  "weight-scale",
  "weight",
  "wheat",
  "wheelchair",
  "whistle-active",
  "whistle",
  "wifi-empty",
  "wifi-full",
  "wifi-high",
  "wifi-low",
  "wifi-slash",
  "wind",
  "wine",
  "xray",
] as const;

export type IconName =
  | "academic-cap"
  | "acorn"
  | "acupuncture"
  | "airplane"
  | "alarm"
  | "alcohol-1"
  | "alcohol-2"
  | "align-bottom-1"
  | "align-bottom-2"
  | "align-center-horizontal-1"
  | "align-center-horizontal-2"
  | "align-center-vertical-1"
  | "align-center-vertical-2"
  | "align-left-1"
  | "align-left-2"
  | "align-right-1"
  | "align-right-2"
  | "align-top-1"
  | "align-top-2"
  | "anchor"
  | "antibody"
  | "apple"
  | "archery"
  | "archive"
  | "arow-shuffle"
  | "arrow-backward-1"
  | "arrow-backward-2"
  | "arrow-bend-down-left-1"
  | "arrow-bend-down-left-2"
  | "arrow-bend-down-right-1"
  | "arrow-bend-down-right-2"
  | "arrow-bend-up-left-1"
  | "arrow-bend-up-left-2"
  | "arrow-bend-up-right-1"
  | "arrow-bend-up-right-2"
  | "arrow-down-circle"
  | "arrow-down-left-circle"
  | "arrow-down-left"
  | "arrow-down-right-circle"
  | "arrow-down-right"
  | "arrow-down-up"
  | "arrow-down"
  | "arrow-fat-down"
  | "arrow-fat-left"
  | "arrow-fat-right"
  | "arrow-fat-up"
  | "arrow-forward-1"
  | "arrow-forward-2"
  | "arrow-horizontal"
  | "arrow-left-circle"
  | "arrow-left-right"
  | "arrow-left"
  | "arrow-line-down"
  | "arrow-line-left"
  | "arrow-line-right"
  | "arrow-line-up"
  | "arrow-maximize"
  | "arrow-minimize"
  | "arrow-omnidirectional-inside-1"
  | "arrow-omnidirectional-inside-2"
  | "arrow-omnidirectional-outside-1"
  | "arrow-omnidirectional-outside-2"
  | "arrow-recycle"
  | "arrow-redo"
  | "arrow-repeat-clockwise-1"
  | "arrow-repeat-clockwise-2"
  | "arrow-repeat-counterclockwise-1"
  | "arrow-repeat-counterclockwise-2"
  | "arrow-reply"
  | "arrow-right-circle"
  | "arrow-right"
  | "arrow-rotate-clockwise-1"
  | "arrow-rotate-counterclockwise-1"
  | "arrow-share"
  | "arrow-sign-in-1"
  | "arrow-sign-in-2"
  | "arrow-sign-out-1"
  | "arrow-sign-out-2"
  | "arrow-skip-backward"
  | "arrow-skip-forward"
  | "arrow-split"
  | "arrow-square-in"
  | "arrow-square-out"
  | "arrow-top-left"
  | "arrow-trend-down"
  | "arrow-trend-up"
  | "arrow-undo"
  | "arrow-up-circle"
  | "arrow-up-left-circle"
  | "arrow-up-right-circle"
  | "arrow-up-right"
  | "arrow-up"
  | "arrow-upload-1"
  | "arrow-upload"
  | "arrow-vector-three"
  | "arrow-vector-two"
  | "arrow-vertical"
  | "asthma-inhaler"
  | "atom"
  | "avocado"
  | "baby-bottle-1"
  | "baby-bottle-2"
  | "baby-crib"
  | "baby-face-1"
  | "baby-face-2"
  | "baby-face-3"
  | "baby-face-4"
  | "baby-stroll"
  | "baby-wrap"
  | "backspace"
  | "bacteria-1"
  | "bacteria-11"
  | "bacteria"
  | "balance"
  | "banana"
  | "bandaid"
  | "bandaids"
  | "bank-1"
  | "bank-2"
  | "barbell-diagonal"
  | "barbell-horizontal"
  | "baseball-bat"
  | "baseball-helmet"
  | "baseball"
  | "basketball"
  | "battery-empty"
  | "battery-full"
  | "battery-high"
  | "battery-low"
  | "battery-medium"
  | "bed"
  | "bell-1"
  | "bell-2"
  | "bell-3"
  | "bell-4"
  | "bell-ringing"
  | "bell-slash-1"
  | "bell-slash-2"
  | "bell-slash-3"
  | "bell-slash-4"
  | "bicep"
  | "bicycle"
  | "bill-medical"
  | "bill"
  | "binocular"
  | "biohazard"
  | "blender-1"
  | "blender-2"
  | "blood-cells-1"
  | "blood-cells-2"
  | "blood-cells-circulation"
  | "bluetooth-active"
  | "bluetooth-slash"
  | "bluetooth"
  | "boat"
  | "body-fat"
  | "body-lotion"
  | "body-wash"
  | "bone-crack"
  | "bone"
  | "book-closed"
  | "book-open"
  | "bookmark"
  | "bookmarks"
  | "bowl-of-hygeia-1"
  | "bowl-of-hygeia-2"
  | "box-cube"
  | "boxing"
  | "brackets-curly"
  | "brackets-round"
  | "brackets-sharp"
  | "brackets-square"
  | "brain-1"
  | "brain-2"
  | "bread-toast"
  | "briefcase-1"
  | "briefcase-2"
  | "briefcase-plus"
  | "broccoli"
  | "browser"
  | "bug"
  | "building-1"
  | "building-2"
  | "building-3"
  | "building-4"
  | "bus"
  | "cake"
  | "calendar-1"
  | "calendar-2"
  | "calendar-check"
  | "calendar-heart"
  | "calendar-minus"
  | "calendar-plus"
  | "calendar-slash-1"
  | "calendar-slash-2"
  | "camera-1"
  | "camera-2"
  | "camera-slash-1"
  | "camera-slash-2"
  | "cancer-cell-1"
  | "cancer-cell-2"
  | "cancer-ribbon"
  | "cannabis"
  | "car-1"
  | "car-2"
  | "car-van"
  | "carrot"
  | "celebration"
  | "cell"
  | "cells"
  | "chart-area"
  | "chart-axis-area"
  | "chart-axis-bar-1"
  | "chart-axis-bar-2"
  | "chart-axis-bar-3"
  | "chart-axis-bar-stacked-1"
  | "chart-axis-bar-stacked-2"
  | "chart-axis-bubble"
  | "chart-axis-line-sharp"
  | "chart-axis-line-wave"
  | "chart-axis-lines"
  | "chart-axis-node"
  | "chart-axis-scatter"
  | "chart-bar-1"
  | "chart-bar-2"
  | "chart-bar-3"
  | "chart-bar-fat-1"
  | "chart-bar-fat-2"
  | "chart-bar-fat-3"
  | "chart-bar-stacked"
  | "chart-bubble"
  | "chart-candlestick-1"
  | "chart-candlestick-2"
  | "chart-decision-tree-1"
  | "chart-decision-tree-2"
  | "chart-decision-tree-3"
  | "chart-donut-1"
  | "chart-donut-2"
  | "chart-node-1"
  | "chart-node-2"
  | "chart-pie-1"
  | "chart-pie-2"
  | "chart-pie-3"
  | "chart-pie-4"
  | "chart-sankey"
  | "chart-trend-down"
  | "chart-trend-up"
  | "chart-waterfall-1"
  | "chart-waterfall-2"
  | "chat-dot"
  | "chat-line"
  | "chat-slash"
  | "chat-smile"
  | "chat"
  | "check-circle"
  | "check"
  | "checks-1"
  | "checks-2"
  | "chef-hat"
  | "cherry"
  | "chevron-double-down-circle"
  | "chevron-double-down"
  | "chevron-double-left-circle"
  | "chevron-double-left"
  | "chevron-double-right-circle"
  | "chevron-double-right"
  | "chevron-double-up-circle"
  | "chevron-double-up"
  | "chevron-down-circle"
  | "chevron-down-up"
  | "chevron-down"
  | "chevron-fat-down"
  | "chevron-fat-left"
  | "chevron-fat-right"
  | "chevron-fat-up"
  | "chevron-left-circle"
  | "chevron-left-right"
  | "chevron-left"
  | "chevron-right-circle"
  | "chevron-right-left"
  | "chevron-right"
  | "chevron-up-circle"
  | "chevron-up-down"
  | "chevron-up"
  | "chicken-drumstick"
  | "chromosome-xx"
  | "chromosome-xy"
  | "cigarette-slash"
  | "cigarette"
  | "clipboard"
  | "clock"
  | "close-x-circle"
  | "close-x"
  | "cloud-1"
  | "cloud-2"
  | "cloud-download-1"
  | "cloud-download-2"
  | "cloud-fog"
  | "cloud-rain-1"
  | "cloud-rain"
  | "cloud-slash-1"
  | "cloud-slash-2"
  | "cloud-snow"
  | "cloud-sun"
  | "cloud-thunder"
  | "cloud-upload-1"
  | "cloud-upload-2"
  | "coffee"
  | "column-item"
  | "column-three"
  | "column-two"
  | "command-key"
  | "compass"
  | "condom"
  | "contact-book"
  | "cookie"
  | "cooking-pot"
  | "copy-1"
  | "copy-2"
  | "corn"
  | "credit-card"
  | "cricket"
  | "crispr"
  | "croissant"
  | "crown-1"
  | "crown-2"
  | "crutches"
  | "currecy-try"
  | "currency-btc"
  | "currency-chf"
  | "currency-cny"
  | "currency-eth"
  | "currency-eur"
  | "currency-gbp"
  | "currency-ils"
  | "currency-inr"
  | "currency-jpy"
  | "currency-krw"
  | "currency-rub"
  | "currency-usd"
  | "cursor-1"
  | "cursor-2"
  | "cursor-text"
  | "dashboard"
  | "database"
  | "dental-equipment"
  | "dermatoscope"
  | "diamond-1"
  | "diamond-2"
  | "divide"
  | "dna"
  | "document-fold"
  | "door"
  | "dot-nine"
  | "dot-six-horizontal"
  | "dot-six-vertical"
  | "dot-three-horizontal"
  | "dot-three-vertical"
  | "dragger"
  | "drone-1"
  | "drone-2"
  | "drug-container-1"
  | "drug-container-2"
  | "drug-powder"
  | "drug-store"
  | "ear-1"
  | "ear-2"
  | "earphone-case"
  | "earphone-left"
  | "earphone-right"
  | "earphones"
  | "ecg-vital-sign"
  | "egg-cracked"
  | "egg-1"
  | "egg-2"
  | "egg-3"
  | "elbow"
  | "email-at"
  | "emergency"
  | "emotion-depressed"
  | "emotion-happy"
  | "emotion-nervous"
  | "emotion-neutral"
  | "emotion-overjoyed"
  | "emotion-sad"
  | "emotion-unhappy"
  | "enema"
  | "envelope-1"
  | "envelope-2"
  | "envelope-open-1"
  | "envelope-open-2"
  | "equal-approximate"
  | "equal"
  | "equalizer"
  | "exclamation-mark-circle"
  | "exclamation-mark-triangle"
  | "exclamation-mark"
  | "eye-closed"
  | "eye-retina"
  | "eye-slash"
  | "eye-water-drop"
  | "eye"
  | "eyedropper"
  | "face-depressed"
  | "face-happy"
  | "face-id"
  | "face-mask-1-1"
  | "face-mask-1"
  | "face-mask-2"
  | "face-neutral"
  | "face-overjoyed"
  | "face-sad"
  | "fast-food"
  | "feces"
  | "female-waist-genital"
  | "female-waist-heart"
  | "female-waist-underwear"
  | "fetus"
  | "file-1"
  | "file-2"
  | "file-archive"
  | "file-check"
  | "file-download"
  | "file-lab-test"
  | "file-magnifying-glass"
  | "file-minus"
  | "file-plus"
  | "file-upload"
  | "file-x"
  | "film-strip"
  | "fingerprint-1"
  | "fingerprint-2"
  | "fire-1"
  | "fire-2"
  | "fire-truck"
  | "fish"
  | "fitness-bike-1"
  | "fitness-bike-2"
  | "fitness-bike-3"
  | "flag-1"
  | "flag-2"
  | "flashlight"
  | "flask-circle"
  | "flask-triangle"
  | "floppy-disk-1"
  | "floppy-disk-2"
  | "flower-fertile"
  | "folder-archive"
  | "folder-open"
  | "folder"
  | "foot-step"
  | "foot-steps"
  | "foot"
  | "forbidden-circle"
  | "forbidden-square"
  | "fork-knife"
  | "fork-spoon"
  | "four-diamonds"
  | "funnel-1"
  | "funnel-2"
  | "funnel-3"
  | "funnel-4"
  | "game-controller"
  | "garlic"
  | "gauge-1"
  | "gauge-2"
  | "gavel-1"
  | "gavel-2"
  | "gear-1"
  | "gear-2"
  | "gender-female"
  | "gender-male"
  | "gender-transgender"
  | "gift"
  | "globe"
  | "glucose"
  | "golf"
  | "grapefruit"
  | "grid-four"
  | "grid-nine"
  | "hair-brush"
  | "hair-comb-1"
  | "hair-comb-2"
  | "hamburger"
  | "hammer"
  | "hand-coin"
  | "hand-grip"
  | "hand-health-cross"
  | "hand-heart"
  | "hand-massage"
  | "hand-mirror"
  | "hand-pan"
  | "hand-pill"
  | "hand-pointing"
  | "hand-skeleton"
  | "hand-stop"
  | "hand-swipe-left"
  | "hand-swipe-right"
  | "hand-touch"
  | "hand-wash-1"
  | "hand-wash-2"
  | "hand"
  | "hands-health-cross"
  | "handshake"
  | "hard-drive"
  | "hash-tag-1"
  | "hash-tag-2"
  | "head-acupuncture"
  | "head-cognition"
  | "head-ent"
  | "head-plus"
  | "head-sneeze"
  | "head-spiral"
  | "head"
  | "headphone-1"
  | "headphone-2"
  | "headset-1"
  | "headset-2"
  | "health-cross-1"
  | "health-cross-2"
  | "health-cross-3"
  | "hearing-aid-1"
  | "hearing-aid-2"
  | "heart-1"
  | "heart-broken"
  | "heart-check"
  | "heart-ecg"
  | "heart-wellness-1"
  | "heart-wellness-2"
  | "heart"
  | "helicopter"
  | "hockey"
  | "hospital-h"
  | "hospital"
  | "hourglass-1"
  | "hourglass-2"
  | "house-1"
  | "house-2"
  | "house-3"
  | "ice-cream"
  | "ice-skating"
  | "identity-card-1"
  | "identity-card-2"
  | "image-1"
  | "image-2"
  | "info-circle"
  | "info"
  | "intestine-1"
  | "intestine-2"
  | "invoice"
  | "iv-bag-1"
  | "iv-bag-2"
  | "jumping-rope"
  | "kebab"
  | "kettlebell"
  | "key-1"
  | "key-2"
  | "keyboard-1"
  | "keyboard-2"
  | "keyboard-3"
  | "kidney"
  | "kidneys-2"
  | "kidneys"
  | "knee"
  | "knife"
  | "landscape"
  | "laptop-mobile"
  | "laptop"
  | "layer-three"
  | "layer-two"
  | "leaf"
  | "leaves-1"
  | "leaves-2"
  | "letter-a-circle"
  | "letter-a"
  | "letter-b-circle"
  | "letter-b"
  | "letter-c-circle"
  | "letter-c"
  | "letter-d-circle"
  | "letter-d"
  | "letter-e-circle"
  | "letter-e"
  | "letter-f-circle"
  | "letter-f"
  | "letter-g-circle"
  | "letter-g"
  | "letter-h-circle"
  | "letter-h"
  | "letter-i-circle"
  | "letter-i"
  | "letter-j-circle"
  | "letter-j"
  | "letter-k-circle"
  | "letter-k"
  | "letter-l-circle"
  | "letter-l"
  | "letter-m-circle"
  | "letter-m"
  | "letter-n-circle"
  | "letter-n"
  | "letter-o-circle"
  | "letter-o"
  | "letter-p-circle"
  | "letter-p"
  | "letter-q-circle"
  | "letter-q"
  | "letter-r-circle"
  | "letter-r"
  | "letter-s-circle"
  | "letter-s"
  | "letter-t-circle"
  | "letter-t"
  | "letter-u-circle"
  | "letter-u"
  | "letter-v-circle"
  | "letter-v"
  | "letter-w-circle"
  | "letter-w"
  | "letter-x-circle"
  | "letter-x"
  | "letter-y-circle"
  | "letter-y"
  | "letter-z-circle"
  | "letter-z"
  | "lifebuoy"
  | "light-bulb-1-active"
  | "light-bulb-1"
  | "light-bulb-2-active"
  | "light-bulb-2"
  | "lightning-bolt-1"
  | "lightning-bolt-2"
  | "lightning-bolt-3"
  | "lightning-bolt-slash-1"
  | "lightning-bolt-slash-2"
  | "lightning-bolt-slash-3"
  | "link-1"
  | "link-2"
  | "link-3"
  | "link-4"
  | "link-break-1"
  | "link-break-2"
  | "lipstick"
  | "list-three-bullet"
  | "list-three-check"
  | "list-three-square"
  | "list-two-bullet"
  | "list-two-check"
  | "list-two-square"
  | "liver-1"
  | "liver-2"
  | "lock-1"
  | "lock-2"
  | "lock-unlocked-1"
  | "lock-unlocked-2"
  | "lung"
  | "magnet"
  | "magnifying-glass-minus"
  | "magnifying-glass-plus"
  | "magnifying-glass"
  | "mailbox"
  | "makeup-brush"
  | "map-pin-1"
  | "map-pin-2"
  | "map-pin-3"
  | "map-pin-4"
  | "map-street"
  | "map-trifold"
  | "margin"
  | "mascara"
  | "mask-happy-sad"
  | "mask-happy"
  | "mask-sad"
  | "massage-acupuncture"
  | "maximize"
  | "measuring-tape"
  | "medal"
  | "medical-card-1"
  | "medical-card-2"
  | "medical-oral-device"
  | "medical-scissor"
  | "medical-tweezer"
  | "megaphone"
  | "menstrual-pad"
  | "menu-center"
  | "menu-grid-1"
  | "menu-left"
  | "menu-right"
  | "microphone-slash"
  | "microphone"
  | "microscope-1"
  | "microscope-2"
  | "milk-carton"
  | "minimize"
  | "minus-circle"
  | "minus-fat-circle"
  | "minus-fat"
  | "minus"
  | "mobile"
  | "molecule-1"
  | "molecule-2"
  | "molecule-honeycomb"
  | "molecules"
  | "monitor"
  | "moon"
  | "moped"
  | "mortar-and-pestle-1"
  | "mortar-and-pestle-2"
  | "motorcycle"
  | "mouse-1"
  | "mouse-2"
  | "mouse"
  | "mouth-wash"
  | "music-note-1"
  | "music-note-2"
  | "nail-polish"
  | "newspaper-1"
  | "newspaper-2"
  | "nose"
  | "notches"
  | "note-1"
  | "note-2"
  | "note-pencil"
  | "number-binary"
  | "number-eight-circle"
  | "number-eight"
  | "number-five-circle"
  | "number-five"
  | "number-four-circle"
  | "number-four"
  | "number-nine-circle"
  | "number-nine"
  | "number-one-circle"
  | "number-one"
  | "number-seven-circle"
  | "number-seven"
  | "number-six-circle"
  | "number-six"
  | "number-three-circle"
  | "number-three"
  | "number-two-circle"
  | "number-two"
  | "number-zero-circle"
  | "number-zero"
  | "nurse-hat"
  | "option-key"
  | "orange"
  | "otoscope"
  | "ovarium-1"
  | "ovarium-2"
  | "oven"
  | "oxygen-tank"
  | "padding"
  | "palette"
  | "paper-clip-1"
  | "paper-clip-2"
  | "paper-money"
  | "paper-plane-diagonal"
  | "paper-plane-horizontal"
  | "paper-plane-vertical"
  | "passport"
  | "path-1"
  | "path-2"
  | "pause-circle"
  | "pause"
  | "paw"
  | "peanut"
  | "pen"
  | "pencil-1"
  | "pencil-2"
  | "pencil-line-1"
  | "pencil-line-2"
  | "percentage-circle"
  | "percentage"
  | "person-acrobatics"
  | "person-arms-spread"
  | "person-biking"
  | "person-dodgeball"
  | "person-elderly-female"
  | "person-elderly-male"
  | "person-hiking"
  | "person-injured"
  | "person-karate"
  | "person-man-1"
  | "person-man-2"
  | "person-man-hands-up"
  | "person-meditation"
  | "person-pregnant-woman"
  | "person-rowing"
  | "person-running"
  | "person-skating"
  | "person-sleep-plus"
  | "person-sleep"
  | "person-soccer"
  | "person-swimming"
  | "person-walking"
  | "person-wheelchair"
  | "person-woman-1"
  | "person-woman-2"
  | "person-woman-hands-up"
  | "person-yoga"
  | "petri-dish-1"
  | "petri-dish-2"
  | "petri-dish-3"
  | "petri-dish-4"
  | "piggy-bank"
  | "pill-circle"
  | "pill-diamond"
  | "pill-hexagon"
  | "pill-oval"
  | "pill-pentagon"
  | "pill-ring"
  | "pill-round-long"
  | "pill-square-long"
  | "pill-square"
  | "pill-triangle"
  | "pin-1"
  | "pin-2"
  | "pizza"
  | "plant-pot"
  | "play-circle"
  | "play"
  | "plus-circle"
  | "plus-fat-circle"
  | "plus-fat"
  | "plus"
  | "pollen"
  | "power-cable"
  | "power"
  | "pregnancy-test"
  | "prescription"
  | "price-tag"
  | "printer"
  | "processor-cpu"
  | "psychiatry"
  | "puzzle"
  | "qr-code"
  | "question-mark-circle"
  | "question-mark"
  | "quotes"
  | "radioactive"
  | "ramen"
  | "record-1"
  | "record-2"
  | "refrigerator"
  | "ribcage"
  | "rice-cooker"
  | "rna"
  | "robot-1"
  | "robot-2"
  | "robot-3"
  | "robot-face-1"
  | "robot-face-2"
  | "robot-face-3"
  | "rocket-diagonal-1"
  | "rocket-diagonal-2"
  | "rocket"
  | "rod-of-asclepius"
  | "roller-skating"
  | "row-item"
  | "row-three"
  | "row-two"
  | "rugby"
  | "ruler-1"
  | "ruler-2"
  | "rx"
  | "sanitizer"
  | "scalpel"
  | "scan-1"
  | "scan-2"
  | "scissors"
  | "scooter"
  | "seal-check"
  | "server-1"
  | "server-2"
  | "shape-circle-half"
  | "shape-circle"
  | "shape-diamond"
  | "shape-hexagon"
  | "shape-pentagon"
  | "shape-rectangle-1"
  | "shape-rectangle-2"
  | "shape-square"
  | "shape-triangle"
  | "shapes-triangle-square-circlce"
  | "share-1"
  | "share-2"
  | "shield-check"
  | "shield-exclamation-mark"
  | "shield-plus"
  | "shield-slash"
  | "shield"
  | "shopping-bag"
  | "shopping-cart-1"
  | "shopping-cart-2"
  | "shower-1"
  | "shower-2"
  | "shrimp"
  | "shuttlecock"
  | "sidebar-left"
  | "sidebar-right"
  | "siren"
  | "skillet"
  | "skin-1"
  | "skin-2"
  | "skull"
  | "sleep-zzz"
  | "slider-dot-three-horizontal"
  | "slider-dot-three-vertical"
  | "slider-dot-two-horizontal"
  | "slider-dot-two-vertical"
  | "slider-line-three-horizontal"
  | "slider-line-three-vertical"
  | "slider-line-two-horizontal"
  | "slider-line-two-vertical"
  | "smart-watch-ekg"
  | "smart-watch-plus"
  | "smart-watch"
  | "smile-depressed"
  | "smile-happy"
  | "smile-neutral"
  | "smile-overjoyed"
  | "smile-sad"
  | "snowflake-1"
  | "snowflake-2"
  | "soccer-field"
  | "soccer"
  | "sort-ascending"
  | "sort-descending"
  | "soybean"
  | "spanner"
  | "sparkle-1"
  | "sparkle-2"
  | "sperm-2"
  | "sperm"
  | "spine-1"
  | "spine"
  | "squid"
  | "star-circle"
  | "star-four"
  | "star-full"
  | "star-half"
  | "stem-cell-1"
  | "stem-cell-2"
  | "step-sneaker"
  | "stethoscope-arrow-left"
  | "stethoscope-arrow-right"
  | "stethoscope-check"
  | "stethoscope-mobile"
  | "stethoscope"
  | "stomach-1"
  | "stomach"
  | "stop-circle"
  | "stop"
  | "stopwatch"
  | "storefront-1"
  | "storefront-2"
  | "strawberry"
  | "sugar-bag"
  | "sun"
  | "syringe-1"
  | "syringe-2"
  | "table-mirror"
  | "table"
  | "tablet"
  | "takeout-food"
  | "tampon-1"
  | "tampon-2"
  | "target-1"
  | "target-2"
  | "teeth"
  | "telephone-1"
  | "telephone-2"
  | "telephone-arrow-down-left-1"
  | "telephone-arrow-down-left-2"
  | "telephone-arrow-right-1"
  | "telephone-arrow-right-2"
  | "telephone-arrow-up-right-1"
  | "telephone-arrow-up-right-2"
  | "telephone-horizontal-1"
  | "telephone-horizontal-2"
  | "telephone-plus-1"
  | "telephone-plus-2"
  | "telephone-x-1"
  | "telephone-x-2"
  | "temperature-high"
  | "temperature-low"
  | "temperature-medium"
  | "tennis-1"
  | "tennis"
  | "test-tube-1"
  | "test-tube-2"
  | "test-tube-3"
  | "text-a"
  | "text-align-center"
  | "text-align-justified"
  | "text-align-left"
  | "text-align-right"
  | "text-b"
  | "text-columns"
  | "text-field"
  | "text-h"
  | "text-i-italic"
  | "text-indent"
  | "text-outdent"
  | "text-t"
  | "text-u-underline"
  | "thumbs-down"
  | "thumbs-up"
  | "ticket"
  | "tie"
  | "tilde"
  | "toggle-left"
  | "toggle-right"
  | "tooth-brace"
  | "tooth-crown"
  | "tooth-floss"
  | "tooth-implant"
  | "tooth"
  | "toothbrush-1"
  | "toothbrush-2"
  | "toothbrush-3"
  | "torso-skeleton"
  | "tounge"
  | "tractor"
  | "train-1"
  | "train-2"
  | "translate"
  | "trash-1"
  | "trash-2"
  | "tray"
  | "treadmill"
  | "tree"
  | "trophy-1"
  | "trophy-2"
  | "truck-ambulance"
  | "truck-delivery"
  | "truck"
  | "tv"
  | "tweezer"
  | "umbrella"
  | "user-check"
  | "user-minus"
  | "user-plus"
  | "user-x"
  | "user"
  | "users-three"
  | "users-two"
  | "vaccine"
  | "vibrate"
  | "video-slash"
  | "video"
  | "virus-1"
  | "virus-2"
  | "volleyball"
  | "volume-high"
  | "volume-low"
  | "volume-none"
  | "volume-slash"
  | "volume-x"
  | "walking-aid"
  | "wallet"
  | "water-bottle-1"
  | "water-bottle-2"
  | "water-bottle-3"
  | "water-drop-minus"
  | "water-drop-plus"
  | "water-drop"
  | "water-glass-empty"
  | "water-glass-high"
  | "water-glass-low"
  | "water-glass-medium"
  | "wave-saw"
  | "wave-sine"
  | "wave-square"
  | "wave"
  | "weight-scale-minus"
  | "weight-scale-plus"
  | "weight-scale"
  | "weight"
  | "wheat"
  | "wheelchair"
  | "whistle-active"
  | "whistle"
  | "wifi-empty"
  | "wifi-full"
  | "wifi-high"
  | "wifi-low"
  | "wifi-slash"
  | "wind"
  | "wine"
  | "xray";
