export { discoveryClient } from "./discovery.client";
export type {
  Club,
  ClubClass,
  ClubSlot,
  CreateClassPayload,
  CreateClubPayload,
  CreateSlotPayload,
  ListClassesResponse,
  ListClubsParams,
  ListClubsResponse,
  ListSlotsResponse,
  Reservation,
  ReserveSlotPayload,
  DiscoveryArticleItem,
  DiscoveryBannerItem,
  DiscoveryClubItem,
  DiscoveryCoachItem,
  DiscoverySection,
  DiscoverySectionAppearance,
  PublicCatalogClass,
  PublicCatalogClub,
  PublicCatalogCoach,
  PublicCatalogClubType,
  PublicCatalogClubTypesResponse,
  PublicCatalogPage,
  PublicCatalogParams,
  PublicCatalogSearchResponse,
  PublicResourceItem,
  PublicResourcePage,
} from "./discovery.dto";
export { discoveryEndpoints } from "./discovery.endpoints";
export {
  useClub,
  useClubClasses,
  useClubSlots,
  useDiscoveryFeed,
  useClubs,
  useCreateClass,
  useCreateClub,
  useCreateSlot,
  useReserveSlot,
  useCatalogClubs,
  useCatalogClub,
  useCatalogCoaches,
  useCatalogCoach,
  useCatalogClasses,
  useCatalogClass,
  useCatalogSearch,
  useCatalogClubTypes,
  usePublicCatalogResource,
} from "./discovery.hooks";
export { discoveryQueries } from "./discovery.queries";
