import { tv } from "tailwind-variants";

export const discoveryClubSlotsScreenStyles = tv({
  slots: {
    root: "relative isolate mx-auto w-full max-w-xl overflow-x-clip bg-background pb-[max(1rem,env(safe-area-inset-bottom))]",
    hero: "relative isolate mx-3 h-[20rem] overflow-hidden rounded-t-[var(--app-radius-feature,24px)] sm:mx-4 sm:h-[23rem]",
    coverWrap: "pointer-events-none absolute inset-0 overflow-hidden",
    cover: "size-full object-cover",
    overlay: "pointer-events-none absolute inset-0 bg-linear-to-t from-background/90 via-background/40 to-background/10",
    heroCopy: "relative z-10 flex h-full flex-col items-center justify-center gap-2 px-5 pb-20 text-center text-foreground",
    heroEyebrow: "text-xs font-semibold",
    heroTitle: "text-4xl font-black leading-tight sm:text-5xl",
    heroSubtitle: "max-w-full text-balance text-sm font-semibold leading-6",
    chipRow: "absolute inset-x-0 bottom-10 z-20 px-4",
    chipScroller: "w-full pb-1",
    chipContent: "flex w-max gap-2",
    chipButton: "shrink-0 rounded-full text-xs font-semibold outline-none transition-colors focus-visible:ring-2 focus-visible:ring-focus",
    chipActive: "border border-accent bg-accent text-accent-foreground",
    chipIdle: "border border-border/60 bg-surface/85 text-foreground backdrop-blur-md",
    panel: "relative z-30 mx-3 -mt-6 rounded-[var(--app-radius-feature,24px)] border border-border/60 bg-surface p-4 shadow-sm sm:mx-4 sm:p-5",
    panelBody: "space-y-5",
    panelContent: "space-y-5",
    section: "space-y-3",
    sectionLabel: "flex items-center gap-2 text-sm font-semibold text-foreground",
    sectionIcon: "grid size-5 shrink-0 place-items-center text-muted",
    radioRow: "w-full pb-1",
    dateTabs: "w-max",
    dateTabsListContainer: "rounded-none bg-transparent p-0",
    dateTabsList: "flex w-max gap-2 rounded-none border-0 bg-transparent p-0",
    dateTab: "group flex min-h-20 min-w-[4.25rem] shrink-0 flex-col items-center justify-center gap-2 rounded-[var(--app-radius-control,16px)] border border-transparent !bg-surface-secondary px-3 py-3 !text-foreground opacity-100 transition-colors data-[selected=true]:border-foreground data-[selected=true]:!bg-surface data-[selected=true]:!text-foreground focus-visible:outline-2 focus-visible:outline-focus",
    dateTabIndicator: "hidden",
    dateDay: "text-2xl font-semibold tabular-nums leading-none",
    dateWeekday: "text-xs font-medium text-muted group-data-[selected=true]:text-foreground",
    timeRadio: "group min-w-0 w-full data-[disabled=true]:opacity-40",
    timeArea: "min-w-0",
    timeScroller: "w-full pb-1",
    timeGroup: "grid w-full grid-cols-2 gap-2",
    timeEmpty: "flex min-h-28 w-full flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-border bg-surface-secondary px-4 py-4 text-center text-sm text-muted",
    timeEmptyImage: "size-12 object-cover",
    timeContent: "flex min-h-12 w-full items-center justify-center rounded-[var(--app-radius-control,16px)] border border-transparent !bg-surface-secondary px-2 py-3 text-center text-sm font-semibold tabular-nums !text-foreground transition-colors group-data-[focus-visible=true]:outline-2 group-data-[focus-visible=true]:outline-focus",
    timeContentSelected: "border-accent !bg-accent/10 !text-foreground",
    footer: "flex flex-wrap items-center justify-between gap-4 pt-4",
    footerSticky: "border-t border-border bg-surface",
    priceLabel: "text-xs font-medium text-muted",
    priceValue: "mt-1 text-xl font-bold text-foreground tabular-nums",
    bookButton: "min-w-36 flex-1 sm:max-w-60",
    empty: "flex flex-col items-center justify-center gap-4 py-8 text-center",
    emptyImage: "size-28 object-cover",
    emptyText: "max-w-[28ch] text-sm leading-6 text-muted",
    controlHidden: "sr-only",
  },
});
