import type { CreateDiscoverySectionDto } from "./dto/discovery-section.dto";

type DefaultDiscoverySection = CreateDiscoverySectionDto & {
  position: number;
};

const appearance = {
  backgroundColor: "transparent",
  textColor: "",
  accentColor: "",
  showHeader: true,
  showViewAll: true,
  headerAlignment: "start",
  viewAllVariant: "link",
} as const;

export const DEFAULT_DISCOVERY_SECTIONS = [
  {
    key: "featured-banners",
    type: "banners",
    title: "پیشنهادهای ویژه",
    subtitle: "فرصت‌های تازه برای شروع حرکت",
    layout: "16/9:1",
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: { ...appearance },
    enabled: true,
    position: 0,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "newest",
      filters: {},
    },
    banners: [
      {
        title: "باشگاه مناسب خودت را پیدا کن",
        subtitle: "بهترین باشگاه‌ها و مربی‌ها، یک‌جا و نزدیک تو",
        imageUrl: "/welcome/introduce/discover-iran-v2.png",
        actionLabel: "شروع جست‌وجو",
        actionUrl: "/discovery/search",
      },
      {
        title: "با مربی حرفه‌ای تمرین کن",
        subtitle: "مربی مناسب هدفت را انتخاب کن",
        imageUrl: "/welcome/introduce/book-iran-v2.png",
        actionLabel: "مشاهده مربی‌ها",
        actionUrl: "/discovery/coaches",
      },
    ],
  },
  {
    key: "top-rated-clubs",
    type: "clubs",
    title: "باشگاه‌های محبوب",
    subtitle: "انتخاب کاربران جیم‌فورمی",
    layout: "editorial",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/clubs",
    appearance: { ...appearance },
    enabled: true,
    position: 1,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 8,
      sort: "rating",
      filters: {},
    },
    banners: [],
  },
  {
    key: "featured-coaches",
    type: "coaches",
    title: "مربی‌های منتخب",
    subtitle: "کنار حرفه‌ای‌ها به هدفت برس",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: { ...appearance },
    enabled: true,
    position: 2,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 8,
      sort: "rating",
      filters: {},
    },
    banners: [],
  },
  {
    key: "featured-classes",
    type: "classes",
    title: "کلاس‌های پیشنهادی",
    subtitle: "کلاس‌های فعال و آماده ثبت‌نام",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/classes",
    appearance: { ...appearance },
    enabled: true,
    position: 3,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 8,
      sort: "newest",
      filters: {},
    },
    banners: [],
  },
  {
    key: "latest-articles",
    type: "articles",
    title: "تازه‌های مجله",
    subtitle: "تمرین بهتر، تغذیه سالم‌تر و زندگی فعال‌تر",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/articles",
    appearance: { ...appearance },
    enabled: true,
    position: 4,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 8,
      sort: "newest",
      filters: {},
    },
    banners: [],
  },
  {
    key: "new-coaches",
    type: "coaches",
    title: "مربی‌های تازه‌وارد",
    subtitle: "با چهره‌های تازه دنیای ورزش آشنا شو",
    layout: "compact",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: { ...appearance },
    enabled: true,
    position: 5,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 8,
      sort: "newest",
      filters: {},
    },
    banners: [],
  },
  {
    key: "article-library",
    type: "articles",
    title: "مطالب منتخب برای تو",
    subtitle: "راهنماهای کاربردی برای تمرین و سبک زندگی سالم",
    layout: "horizontal-outline",
    viewAllLabel: "همه مقاله‌ها",
    viewAllUrl: "/discovery/articles",
    appearance: { ...appearance },
    enabled: true,
    position: 6,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 12,
      sort: "name",
      filters: {},
    },
    banners: [],
  },
  {
    key: "discovery-guides",
    type: "banners",
    title: "از کجا شروع کنم؟",
    subtitle: "مسیرهای سریع برای رسیدن به انتخاب مناسب",
    layout: "16/9:1.2",
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: { ...appearance },
    enabled: true,
    position: 7,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "newest",
      filters: {},
    },
    banners: [
      {
        title: "کلاس مناسب برنامه‌ات را پیدا کن",
        subtitle: "زمان و رشته دلخواهت را انتخاب کن",
        imageUrl: "/welcome/introduce/progress-iran-v2.png",
        actionLabel: "دیدن کلاس‌ها",
        actionUrl: "/discovery/classes",
      },
      {
        title: "باشگاه‌های نزدیک روی نقشه",
        subtitle: "انتخاب‌های اطرافت را سریع مقایسه کن",
        imageUrl: "/permissions/location.png",
        actionLabel: "باز کردن نقشه",
        actionUrl: "/discovery/map",
      },
    ],
  },
  {
    key: "discovery-quick-paths",
    type: "banners",
    title: "انتخاب سریع",
    subtitle: "راه‌های کوتاه‌تر برای پیدا کردن گزینه مناسب",
    layout: "4/3:auto",
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: { ...appearance, accentColor: "#18f47b" },
    enabled: true,
    position: 8,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "newest",
      filters: {},
    },
    banners: [
      {
        title: "باشگاه‌های شهر تو",
        subtitle: "انتخاب‌های محبوب را نزدیک خودت ببین",
        imageUrl: "/discovery/locations/city-modern.jpg",
        actionLabel: "انتخاب شهر",
        actionUrl: "/discovery/cities",
      },
      {
        title: "رشته مورد علاقه‌ات",
        subtitle: "از بدنسازی تا ورزش‌های گروهی",
        imageUrl: "/discovery/locations/city-heritage.jpg",
        actionLabel: "مشاهده رشته‌ها",
        actionUrl: "/discovery/search",
      },
      {
        title: "مربی همراه تو",
        subtitle: "بر اساس هدف و سبک تمرین انتخاب کن",
        imageUrl: "/profile/cover.jpg",
        actionLabel: "دیدن مربی‌ها",
        actionUrl: "/discovery/coaches",
      },
    ],
  },
  {
    key: "discovery-stories",
    type: "banners",
    title: "پیشنهادهای امروز",
    subtitle: "کارت‌های عمودی برای کشف سریع‌تر",
    layout: "3/4:auto",
    viewAllLabel: "",
    viewAllUrl: "",
    appearance: { ...appearance, headerAlignment: "center" },
    enabled: true,
    position: 9,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "newest",
      filters: {},
    },
    banners: [
      {
        title: "اولین جلسه‌ات را رزرو کن",
        subtitle: "کلاس‌های فعال و آماده ثبت‌نام",
        imageUrl: "/welcome/introduce/book-iran-v2.png",
        actionLabel: "رزرو کلاس",
        actionUrl: "/discovery/classes",
      },
      {
        title: "نزدیک‌ترین انتخاب‌ها",
        subtitle: "روی نقشه اطرافت را جست‌وجو کن",
        imageUrl: "/permissions/location.png",
        actionLabel: "مشاهده نقشه",
        actionUrl: "/discovery/map",
      },
      {
        title: "راهنمای تمرین بهتر",
        subtitle: "مطالب تازه و کاربردی مجله",
        imageUrl: "/welcome/introduce/progress-iran-v2.png",
        actionLabel: "مطالعه مقاله‌ها",
        actionUrl: "/discovery/articles",
      },
    ],
  },
  {
    key: "popular-sports",
    type: "sports",
    title: "رشته‌های محبوب",
    subtitle: "ورزش مناسب هدفت را پیدا کن",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: { ...appearance },
    enabled: true,
    position: 10,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 12,
      sort: "name",
      filters: {},
    },
    banners: [],
  },
  {
    key: "ball-sports",
    type: "sports",
    title: "ورزش‌های توپی",
    subtitle: "از فوتبال و والیبال تا بسکتبال",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: { ...appearance },
    enabled: true,
    position: 11,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "name",
      filters: { categoryCodes: ["BALL_SPORTS"] },
    },
    banners: [],
  },
  {
    key: "mind-body-sports",
    type: "sports",
    title: "ذهن و بدن",
    subtitle: "یوگا، پیلاتس و تمرین‌های آرامش‌بخش",
    layout: "carousel",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: { ...appearance },
    enabled: true,
    position: 12,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "name",
      filters: { categoryCodes: ["MIND_BODY"] },
    },
    banners: [],
  },
  {
    key: "online-coaches",
    type: "coaches",
    title: "مربی‌های آنلاین",
    subtitle: "هرجا هستی با مربی حرفه‌ای تمرین کن",
    layout: "compact",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/coaches",
    appearance: { ...appearance },
    enabled: true,
    position: 13,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "rating",
      filters: { serviceModes: ["online"] },
    },
    banners: [],
  },
  {
    key: "discovery-portrait-stories",
    type: "banners",
    title: "داستان‌های ورزشی",
    subtitle: "پیشنهادهای کوتاه برای شروع یک تجربه تازه",
    layout: "9/16:auto",
    viewAllLabel: "مشاهده همه",
    viewAllUrl: "/discovery/search",
    appearance: { ...appearance },
    enabled: true,
    position: 14,
    selection: {
      mode: "query",
      itemIds: [],
      limit: 10,
      sort: "newest",
      filters: {},
    },
    banners: [
      {
        title: "تمرین امروزت را انتخاب کن",
        subtitle: "باشگاه، کلاس یا مربی؛ انتخاب با توست",
        imageUrl: "/welcome/hero-iran-v2.png",
        actionLabel: "شروع کشف",
        actionUrl: "/discovery/search",
      },
      {
        title: "با یک مربی تازه آشنا شو",
        subtitle: "پروفایل مربی‌ها و برنامه‌هایشان را ببین",
        imageUrl: "/profile/cover.jpg",
        actionLabel: "دیدن مربی‌ها",
        actionUrl: "/discovery/coaches",
      },
      {
        title: "یک کلاس تازه امتحان کن",
        subtitle: "کلاس‌های نزدیک و آماده ثبت‌نام",
        imageUrl: "/welcome/introduce/book-iran-v2.png",
        actionLabel: "دیدن کلاس‌ها",
        actionUrl: "/discovery/classes",
      },
    ],
  },
] satisfies readonly DefaultDiscoverySection[];
