import { generateFonts } from "fantasticon";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = path.join(root, "icons", "duotone");
const tmpDir = path.join(root, "scripts", ".icon-tmp");
const fontOutDir = path.join(root, "fonts", "icons");
const cssOutPath = path.join(root, "src", "icons.css");
const namesOutPath = path.join(root, "src", "icon-names.ts");

const SHAPE_RE =
  /<(path|circle|rect|ellipse|polygon|polyline)(\s[^>]*)?\/>/gi;

function toIconName(fileName) {
  return fileName
    .replace(/\.svg$/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function isSecondaryShape(shape) {
  return /fill-opacity\s*=\s*["']0\.2["']/i.test(shape);
}

function stripSecondaryOpacity(shape) {
  return shape.replace(/\sfill-opacity\s*=\s*["']0\.2["']/gi, "");
}

function wrapSvg(viewBox, inner) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${inner}</svg>\n`;
}

function splitDuotone(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/i)?.[1] ?? "0 0 24 24";
  const shapes = [...svg.matchAll(SHAPE_RE)].map((match) => match[0]);
  const primary = [];
  const secondary = [];

  for (const shape of shapes) {
    if (isSecondaryShape(shape)) {
      secondary.push(stripSecondaryOpacity(shape));
    } else {
      primary.push(shape);
    }
  }

  return {
    viewBox,
    primary: primary.length > 0 ? wrapSvg(viewBox, primary.join("")) : null,
    secondary:
      secondary.length > 0 ? wrapSvg(viewBox, secondary.join("")) : null,
  };
}

function cssContent(codepoints, names) {
  const rules = names
    .map((name) => {
      const primary = codepoints[name];
      const secondary = codepoints[`${name}-secondary`];
      const primaryHex = primary.toString(16);
      const secondaryRule =
        secondary === undefined
          ? ""
          : `\n.icon-${name}::after { content: "\\${secondary.toString(16)}"; }`;

      return `.icon-${name}::before { content: "\\${primaryHex}"; }${secondaryRule}`;
    })
    .join("\n");

  return `/* Generated by scripts/build-icons.mjs — do not edit. */

@font-face {
  font-family: "FreudDuotone";
  src: url("../fonts/icons/FreudDuotone.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

@theme inline {
  --font-icon: "FreudDuotone";
}

:root {
  --font-icon: "FreudDuotone";
  --icon-secondary-opacity: 0.2;
}

.icon {
  position: relative;
  display: inline-block;
  flex-shrink: 0;
  width: 1em;
  height: 1em;
  font-family: "FreudDuotone", sans-serif;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  line-height: 1;
  text-transform: none;
  vertical-align: -0.125em;
  speak: never;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon::before,
.icon::after {
  position: absolute;
  inset: 0;
  display: block;
  width: 100%;
  height: 100%;
  font-family: inherit;
  font-style: inherit;
  font-weight: inherit;
  line-height: inherit;
  text-align: center;
}

.icon::before {
  z-index: 1;
  color: currentColor;
}

.icon::after {
  z-index: 0;
  content: none;
  color: currentColor;
  opacity: var(--icon-secondary-opacity);
  pointer-events: none;
}

${rules}
`;
}

function namesContent(names) {
  const union = names.map((name) => `  | "${name}"`).join("\n");
  return `/* Generated by scripts/build-icons.mjs — do not edit. */

export const iconNames = [
${names.map((name) => `  "${name}",`).join("\n")}
] as const;

export type IconName =
${union};
`;
}

async function prepareGlyphs() {
  await rm(tmpDir, { recursive: true, force: true });
  await mkdir(tmpDir, { recursive: true });

  const files = (await readdir(sourceDir))
    .filter((file) => file.endsWith(".svg") && file !== "Icon.svg")
    .sort((a, b) => a.localeCompare(b));

  const names = [];
  const seen = new Set();

  for (const file of files) {
    const name = toIconName(file);
    if (seen.has(name)) {
      throw new Error(`Duplicate icon name after sanitize: ${name} (${file})`);
    }
    seen.add(name);

    const svg = await readFile(path.join(sourceDir, file), "utf8");
    const { primary, secondary } = splitDuotone(svg);

    if (!primary) {
      throw new Error(`No primary paths in ${file}`);
    }

    await writeFile(path.join(tmpDir, `${name}.svg`), primary);
    if (secondary) {
      await writeFile(path.join(tmpDir, `${name}-secondary.svg`), secondary);
    }
    names.push(name);
  }

  return names;
}

async function main() {
  const names = await prepareGlyphs();

  await mkdir(fontOutDir, { recursive: true });

  const result = await generateFonts({
    name: "FreudDuotone",
    inputDir: tmpDir,
    outputDir: fontOutDir,
    fontTypes: ["woff2"],
    assetTypes: [],
    fontHeight: 1000,
    normalize: true,
    descent: 0,
    round: 10e12,
    prefix: "icon",
    selector: ".icon",
  });

  const codepoints = result.codepoints;
  const missing = names.filter((name) => codepoints[name] === undefined);
  if (missing.length > 0) {
    throw new Error(`Missing glyphs: ${missing.slice(0, 12).join(", ")}`);
  }

  await writeFile(cssOutPath, cssContent(codepoints, names));
  await writeFile(namesOutPath, namesContent(names));
  await rm(tmpDir, { recursive: true, force: true });

  console.log(
    `Generated FreudDuotone font with ${names.length} icons (${Object.keys(codepoints).length} glyphs).`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
